### ISSUE TITLE
[CM11]  Camera

### ISSUE THREAD

**Issue by bhanucbs-13** [LegacyXperia/local_manifests#267] opened 2013-12-11 07:03 UTC
Version :alphabuild 2

Recording scene fridge in camera recording mode only recording time running. And also there is no recorded video found in iyokan

**Comment by soulpower11** [comment] 2013-12-11 07:22
Same here. Using xperia neo V

**Comment by KiranAK47** [comment] 2013-12-11 07:47
The issue is in anzu(arc s) too.
Video is not saved in the gallery .

**Comment by dru1988** [comment] 2013-12-11 09:51
Also whit mango.

**Comment by soulpower11** [comment] 2013-12-11 09:55
And camera freezes and force close when taking photos that is under 3MPs and below.

**Comment by mikeNG** [comment] 2013-12-11 18:05
try alpha 3. Provide logs

**Comment by bhanucbs-13** [comment] 2013-12-11 18:07
Same in alpha 3

**Comment by soulpower11** [comment] 2013-12-12 03:20
is this the right log ? http://pastebin.com/Sa3TTQGP for video recording.

and this is the other log for taking pictures http://pastebin.com/G4BGtscP.

it is still the same in alpha 3

**Comment by fotocreaman** [comment] 2013-12-12 16:13
Same for Mango and Alpha 3
Also camera HW button does not activate the app

**Comment by mikeNG** [comment] 2013-12-12 19:30
@soulpower11 take logs exactly after you exit the camera app. These logs you posted are incomplete

**Comment by soulpower11** [comment] 2013-12-13 01:32
This http://pastebin.com/9qAFDeQs ?

and the other log http://pastebin.com/JY1yMctv

**Comment by xange** [comment] 2013-12-14 12:24
@mikeNG  this is my logcat from Xperia Neo. 

http://pastebin.com/Ng1CWExr

hope it helps :-)

logcat from starting camera apps straight into cam mode, start recording 3 seconds, stop recording and exit apps.

**Comment by mikeNG** [comment] 2013-12-14 12:51
There is a general problem with video encoder/decoder in 4.4.
I will look into it.

**Comment by dinoomanovic** [comment] 2013-12-15 13:01
Here's another log, recording 10s video with audio on haida
http://pastebin.com/pQSsxtQy

**Comment by luismytronic** [comment] 2013-12-20 14:43
mismo problema grabacion de video no funciona (CM11-aida)

**Comment by amir900A** [comment] 2013-12-22 18:37
also in smultron in alpha 3 :) app hanging after peressing record button ( in video mode )

**Comment by Esarve** [comment] 2013-12-24 07:04
same here [anzu] app hangs and after pressing stop, camera FCs

**Comment by bhanucbs-13** [comment] 2013-12-27 06:34
video recording still not working in cm-11.0-20131225-NIGHTLY-LegacyXperia-iyokan

**Comment by mikeNG** [comment] 2013-12-28 00:46
Fixed in next build

**Closed as completed by mikeNG** 2013-12-28 00:46 UTC
Labels: bug

**Comment by anoopg87** [comment] 2013-12-28 05:36
(Coconut)video recording is not happening. when start recording it freezes :(

**Comment by mikeNG** [comment] 2013-12-28 05:52
I said "Fixed in next build", not the current build
