### ISSUE TITLE
[CM11-20131212 - MT15i] Can't record, event 480p

### ISSUE THREAD

**Issue by nguyentrunght** [LegacyXperia/local_manifests#333] opened 2013-12-24 10:12 UTC
Hi dev team,
I install the latest nightly 12 Dec with more smooth, less reboot but camera cannot record (in option there are 480p and 720p but both cannot record). Try 3rd app but not luck, Cam still not responsive in record mode, after recording, the live view stop for seconds , can stop but it seems not save to sd card.
Hope this will be fix soon in later release.
Thank team, KK is big CM update for legacy Xperia devices.

**Comment by mikeNG** [comment] 2013-12-24 11:38
duplicate of #267

**Closed as completed by mikeNG** 2013-12-24 11:38 UTC
