### ISSUE TITLE
CM11 (nightly 20131127) -Haida-Browser

### ISSUE THREAD

**Issue by Nikhildangui** [LegacyXperia/local_manifests#221] opened 2013-12-03 18:37 UTC
Browser: i few guys reporting that Default browser is nt working properly, i found it to be working properly most of time but at times its freezes badly. even with lite sites like google search page. leaving webpage non responsive for few seconds. 
(only opera and opera mini works perfect)

**Comment by mikeNG** [comment] 2013-12-03 19:15
Duplicate of #181

Why nobody looks in already open issues??!!!

**Closed as completed by mikeNG** 2013-12-03 19:15 UTC

**Comment by Nikhildangui** [comment] 2013-12-03 19:42
Sorry boss... Extremely sorry will be take care next time

**Comment by Nikhildangui** [comment] 2013-12-03 19:47
actually i could nt find this BUG posted here.. i could see it at XDA legacy xperia thread
