### ISSUE TITLE
CM11-anzu keyboard dictionary import issue

### ISSUE THREAD

**Issue by skiss007** [LegacyXperia/local_manifests#592] opened 2014-05-07 07:24 UTC
Hello Guys,

I'm running cm-11.0-20140319-NIGHTLY-LegacyXperia-anzu on my Arc S and have an issue with importing dictionary to the AOSP keyboard.

Once I tap on "import dict file" I get "Unfortunately, Android Keyboard (AOSP) has stopped" error message. 
Do you have the same problem?

I tried to modify LatinIME.apk but without luck. 
I decompiled it with AndroidMultitool and APKStudio as well, removed unnecessary dict files from res/raw, added main-hu.dict there and edited the values/public.xml to correct dict file names and ID's. Then recompiled and signed it without problem, pushed it to /system/app checked permissions to be 644, reloaded the phone but the keyboard is not working. Even I can not install it from /system/app (I get Parse error "There was a problem parsing the package"). I tried to remove the public.xml from the source and let the tool to rebuild it during compile process, but this was not helped.
I would like to have working LatinIME.apk with English, German and Hungarian only in it. Can you guide me how to build it, or can someone be so kind to compile me a working one? ;-)

Do you have any suggestions how to get this working?

Thanks,
skiss007

**Comment by mikeNG** [comment] 2014-05-12 13:39
Which language dictionary were you trying to import?

**Comment by skiss007** [comment] 2014-05-13 05:42
Hello Mike,

I was trying to import the Hungarian dictionary,but I get those error message as soon as I tap onto "import dictionary file" in keyboard settings...

Thanks,
Skiss007

**Comment by mikeNG** [comment] 2014-05-31 19:07
I have reuploaded the file, can you try again?
If it still crashes, please provide a logcat

**Comment by gabri-hell** [comment] 2014-06-02 16:38
I've tried with russian dictionary on iyokan [CM11], crashed too.
here the logcat :

https://gist.github.com/gabri-hell/ecffb794eea55fd7fa73

**Comment by mikeNG** [comment] 2014-06-02 23:38
Please post the logs in pastebin, gist or something similar so they are in a more readable format

**Comment by gabri-hell** [comment] 2014-06-03 07:29
Ok sorry Mike, I'm not used yet... 
Updated ;o)

**Comment by mikeNG** [comment] 2014-06-03 19:03
Duplicate of #487

**Closed as completed by mikeNG** 2014-06-03 19:03 UTC
Labels: cm-11.0
