### ISSUE TITLE
Arc S,bug with phonebooks contacts!!!!

### ISSUE THREAD

**Issue by izida** [LegacyXperia/local_manifests#721] opened 2014-07-12 15:10 UTC
Well,i have on my sd card vcard file with all my contacs.
When i import vcard file all contacts are here,BUT,afther couple days problems come out.
All contact are gone,phonebook is empty,import again end contacts are back.  
This problem going in circle,afther first install of last room this problem is here afther 3-4 days and afther that,problem occurs 3 times per one day!!!!
Any help with this?

**Comment by izida** [comment] 2014-07-18 15:29
Just me have this problem or?

**Comment by FibreFoX** [comment] 2014-07-18 17:36
I can not confirm this bug, im with arc s, build 11-20140701-anzu, maybe there are other apps u have installed which are clearing your contacts. do you have any entries in your logs?

**Comment by izida** [comment] 2014-07-18 17:46
I have no apps for phonebook,i use this one that come with room.
Where to see this part with logs? Please for guide.

**Comment by izida** [comment] 2014-07-20 17:55
Install new version of room,again format all and reinstall gapps but this shit with contact is still here...

**Comment by FibreFoX** [comment] 2014-07-21 12:16
Do you have google-synchronisation active?

**Comment by izida** [comment] 2014-07-21 17:51
![screenshot_2014-07-21-19-50-04](https://cloud.githubusercontent.com/assets/8144071/3647516/960d5eb2-10ff-11e4-81a2-756d35c0e780.png)

Just this.

**Comment by FibreFoX** [comment] 2014-07-28 07:42
To verify on my own, could you please give me a step-by-step instruction? I'm always using [MyPhoneExplorer](http://www.fjsoft.at/en/) to backup/recover my stuff, maybe thats why i dont have that issue.

**Comment by mikeNG** [comment] 2014-07-28 14:32
Can't reproduce this on any of my 5 devices, never had such issues

**Comment by FibreFoX** [comment] 2014-07-28 16:02
Neither did I, but maybe the way @izida is importing the data may change it. im thinking about "temporary import", when the app is closing everything is killed inside RAM. :) will wait for the step-by-step instructions.

**Comment by izida** [comment] 2014-07-28 17:15
Friend,if I understand you,you want to know how i import vcard file?
If this is question:

People---Import/Export---Import from storage---(small window) Phone-only(local phone acount)---Import one vcard file.   Thats all,afther this contact are copy to phonebook and work ok for some time and than  
problem from first post comes...

**Comment by ShreyasKorgaonkar** [comment] 2014-07-29 10:21
Even I can confirm this problem in my coconut
If u boot in safe mode and then restart your device... All contacts gone
Even when I install watsapp or hike after I sign in...contacts are lost
Some problem is there in phonebook storage

**Comment by mikeNG** [comment] 2014-07-29 15:21
Why are you booting in safe mode?

**Comment by ShreyasKorgaonkar** [comment] 2014-07-29 17:20
i am not booting in safe mode
i restarted the device and i kept in my pocket so it accidentally booted in safe mode
but even leaving the safe mode thing when i sign in watsapp or hike the contacts are gone
even today i just rebooted the device and the contacts are gone
there is some problem for sure

**Comment by mikeNG** [comment] 2014-07-30 09:59
I can't reproduce this in any of my devices. I was using google contact sync but I disabled it to try reproducing this issue, but my contacts are fine.

I see no logs in 20 days so I won't spend more time on this issue

**Closed as completed by mikeNG** 2014-07-30 09:59 UTC
Labels: cannotreproduce

**Comment by darkstar42** [comment] 2014-08-12 05:44
Same problem here. 
I have installed it on an Arc S and after the installation of WhatsApp or after a reboot, all contacts are gone and I have to import them again from the SIM card.
Google sync is disabled.
