### ISSUE TITLE
[Mango] Device does not go into deep sleep if Bluetooth is enabled

### ISSUE THREAD

**Issue by M4711** [LegacyXperia/local_manifests#153] opened 2013-11-20 12:39 UTC
Hi, I have a problem with bluetooth, if I connect headphones battery drain is really fast, from 100% to 15% in 5-6 hours. In BetterBatteryStats, phone is still awake in all this time, 0% in deep sleep. Without BT headphones connected phone still not go into deep sleep. This occurs only when BT is enabled, so this must be a BT bug. Sorry for my poor English and I hope you can understand me.

```
LegacyXperia
Mango
SK17i
build 20131112
cm-10.2
```

![screenshot_2013-11-20-15-14-06](https://f.cloud.github.com/assets/5990592/1582762/e6638222-51f3-11e3-8325-30562318622c.png)
![screenshot_2013-11-20-15-14-31](https://f.cloud.github.com/assets/5990592/1582765/f14fecf2-51f3-11e3-9032-1482199e7b57.png)
![screenshot_2013-11-20-15-13-07](https://f.cloud.github.com/assets/5990592/1582767/f49cb7c8-51f3-11e3-93b2-40f90a429686.png)

**Comment by lanmarc77** [comment] 2013-11-20 18:17
For BT drain see here: https://github.com/LegacyXperia/local_manifests/issues/15

**Comment by mikeNG** [comment] 2013-11-20 19:55
Duplicate of #15

**Closed as completed by mikeNG** 2013-11-20 19:55 UTC
