### ISSUE TITLE
[10.2] Proximity sensor e Light sensor not working at all

### ISSUE THREAD

**Issue by taurelio** [LegacyXperia/local_manifests#460] opened 2014-02-07 21:20 UTC
Proximity sensor e Light sensor not working at all  with latest build on coconut

When making a call or receving a call, screen is always on regardeless the position of the phone near the ear.

Thank you for all your hard work

Logs: https://gist.github.com/taurelio/f65a4f0627199238b846

Release candidate 3 build 20140207

**Comment by mikeNG** [comment] 2014-02-12 15:40
Duplicate of #299 
Check my answer there

**Closed as completed by mikeNG** 2014-02-12 15:40 UTC
