### ISSUE TITLE
[CM10.2, smultron] Screen doesn't turn back on

### ISSUE THREAD

**Issue by wolkenschieber** [LegacyXperia/local_manifests#462] opened 2014-02-08 07:23 UTC
Hi,

I just upgraded to cm-10.2-20140207 on my smultron. I'm facing the issue that once the screen is turned off, it doesn't turn back on.

Following lines from the log seems suspious to me:

I/PowerManagerService(  544): Waking up from sleep...
D/SurfaceFlinger(  230): Screen acquired, type=0 flinger=0xf38478
I/WindowManager(  544): Lock screen displayed!
D/SurfaceControl(  544): Excessive delay in unblankDisplay() while turning screen on: 299ms
D/PhoneApp(  809): mReceiver: ACTION_SCREEN_OFF / ACTION_SCREEN_ON
D/AccelerometerListener(  809): enable(false)

This happens, when I press the power button to unlock the phone again.

**Comment by wolkenschieber** [comment] 2014-02-08 07:47
After some poking around.

The issue is always present. Devices boots up into simlock screen. If the screen switches off here, it can't be turned on again.

I was able to capture the log messages which occur right after pressing the power button and switching the screen off:

```
I/PowerManagerService(  546): Going to sleep by user request...
I/WindowManager(  546): No lock screen!
D/SurfaceFlinger(  229): Screen released, type=0 flinger=0x816478
D/PhoneApp(  813): mReceiver: ACTION_SCREEN_OFF / ACTION_SCREEN_ON
D/AccelerometerListener(  813): enable(false)
D/SurfaceControl(  546): Excessive delay in blankDisplay() while turning screen off: 433ms
D/dalvikvm(  546): JIT code cache reset in 3 ms (1048576 bytes 1/0)
D/PhoneApp(  813): mReceiver: ACTION_SCREEN_OFF / ACTION_SCREEN_ON
D/AccelerometerListener(  813): enable(false)
W/IInputConnectionWrapper(  850): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(  850): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(  850): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(  850): getTextAfterCursor on inactive InputConnection
E/InputEventModelImpl(  746): onStartInput event aborted: com.touchtype.keyboard.inputeventmodel.ExtractedTextUnavailableException: could not obtain extracted text (class com.touchtype.keyboard.inputeventmodel.ExtractedTextUnavailableException)
V/KeyguardHostView(  546): hide transport, gen:3
V/KeyguardHostView(  546): music state changed: 0
D/PhoneStatusBar(  679): disable: < expand icons alerts ticker system_info back home RECENT* clock search >
I/Choreographer(  546): Skipped 48 frames!  The application may be doing too much work on its main thread.
V/KeyguardHostView(  546): hide transport, gen:3
V/KeyguardHostView(  546): music state changed: 0
V/TAG     (  546): bug 7643792: fitSystemWindows([0,25][0,0])
I/Choreographer(  546): Skipped 44 frames!  The application may be doing too much work on its main thread.
D/OpenGLRenderer(  546): GL error from OpenGLRenderer: 0x502
E/OpenGLRenderer(  546):   GL_INVALID_OPERATION
D/PhoneStatusBar(  679): disable: < expand icons alerts ticker system_info BACK* HOME* RECENT CLOCK* search >
```

On pressing the power button again, the log from my first comment appear again:

```
I/PowerManagerService(  546): Waking up from sleep...
D/PhoneApp(  813): mReceiver: ACTION_SCREEN_OFF / ACTION_SCREEN_ON
D/AccelerometerListener(  813): enable(false)
D/SurfaceFlinger(  229): Screen acquired, type=0 flinger=0x816478
I/WindowManager(  546): Lock screen displayed!
D/SurfaceControl(  546): Excessive delay in unblankDisplay() while turning screen on: 296ms
```

The screen stays black, only the buttons back and menu shine.

**Comment by wolkenschieber** [comment] 2014-02-08 08:19
I guess I found a workaround. 
Went to dev options -> hardware accerated rendering. There I set the option "Force GPU-Rendering". So far screen locking and unlocking seems to work. But maybe that's just a coincidence.

**Comment by sidharthgtm** [comment] 2014-02-09 18:10
can be reproduced on cm11 and cm 10.1 . will post log soon.

**Comment by wolkenschieber** [comment] 2014-02-09 21:38
How can that be reproduced on CM10.1? I've been using LXP-10.1 for months and the issue hasn't appeared to me. Still a 10.2 rendering thing for me.

**Comment by mikeNG** [comment] 2014-02-12 15:25
It's probably an issue with our legacy graphics code. Too hard to fix.
With no ION kernel this probably can't be fixed

**Comment by mikeNG** [comment] 2014-02-12 15:27
Duplicate of #367

**Closed as completed by mikeNG** 2014-02-12 15:27 UTC
