### ISSUE TITLE
[Invalid] [11.0] SIP apps doesn't work well.

### ISSUE THREAD

**Issue by taro-k** [LegacyXperia/local_manifests#471] opened 2014-02-11 03:39 UTC
Xperia neo with cm-11.0-20140203.
There seem to have a problem around SIP (Session Initiation Protocol).
- Linphone app: It launches, but I "unfortunately" stops later.
- Fusion-IP app (Japanese carrier): It launches, but cannot receive incoming calls.

If anything I can check for debugging, please let me know. thx!

**Comment by taro-k** [comment] 2014-02-11 05:57
cm-11.0-20140121 also havs this matter, too.

**Comment by mikeNG** [comment] 2014-02-12 15:20
provide logs

**Comment by MardonHH** [comment] 2014-04-02 23:42
why not using inbuild sip/voip function from dialer?

**Comment by taro-k** [comment] 2014-04-04 13:38
Thx! I have just tried again with the latest app and confirmed no problem. Here, I close this issue. Also, I will try to move to built-in sip/voip function, thx!

**Comment by maystar** [comment] 2014-04-13 15:54
Which build shouldn't have this issue? I can't use my phone with any SIP application (including the built-in one). I'm using the latest (?) build  cm-11.0-20140319 for my haida device. The stream is interrupted all the time. The dmesg is spamed with such messages:

```
<6>[16736.380675] wl12xx: state: 0
<3>[16736.812834] [audio_pcm_in.c:audpcm_in_enc_config] sending AUDPREPROC_AUDREC_CMD_ENC_CFG command
<3>[16737.035063] [msm7x30.c:msm_device_put] device freq =48000
<6>[16737.079039] wl12xx: firmware booted (Rev 6.3.10.0.139)
<6>[16737.084227] wl12xx: state: 2
<6>[16737.084532] wl12xx: adding p2p mgmt vif
<3>[16737.112822] [voice.c:voice_auddev_cb_function]  Voice is not at ACQUIRE state
<3>[16737.113158] [voice.c:voice_auddev_cb_function]  device is not at proper state
<3>[16737.123168] [msm7x30.c:msm_device_put] device freq =48000
<6>[16737.146880] wl12xx: Association completed.
<3>[16737.187804] [msm7x30.c:msm_device_put] device freq =48000
<3>[16737.214568] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[16737.214843] wl12xx: Reading FW panic log
<6>[16737.215270] wl12xx: Hardware recovery in progress. FW ver: Rev 6.3.10.0.139
<6>[16737.215544] wl12xx: pc: 0x4bc
<6>[16737.215819] wl12xx: removing interface 90:c1:15:19:ce:6a
<6>[16737.216033] wl12xx: removing interface 90:c1:15:19:ce:69
<6>[16737.220244] ieee80211 phy0: Hardware restart was requested
```

**Comment by taro-k** [comment] 2014-04-14 02:07
I am also using cm-11.0-20140319 for my Hallon. For my case, before installing this ROM, I did
- clean up install, which is with format of /system, /data and /cache, and Wipe Data / Factory Reset.
- Also, install Gapps, of course I don't want, to download the latest SIP app from Android market.

I'm not sure this is the cause, but you may try if you have no other choice. I hope this will help you! (For my case, the cause might be using bit old apk not from Android market, from other phone. But I have not tried built-in SIP function yet.)

**Comment by giraldillo** [comment] 2014-04-20 15:54
Same problem as maystar with cm11.0-20140320 with Xperia Mini (St15i, smultron) here: no VoIP calls possible. 

Tried incoming and outgoing, built-in client, CSipSimple and Fritz Fon. Can connect to SipServer sucessfully but call breaks after about 1/10 of a second (no sound in/out). Sometimes connection is lost immediately, sometimes it holds (without sound).

If you need more information or logs: please provide a link how can I get them or describe in a few words (I am able to open a terminal session and type some comands but I don't now everything in detail).

**Comment by taro-k** [comment] 2014-04-20 16:27
It seems better I reopen this issue.
@giraldillo connect your phone and run
adb logcat

**Comment by mikeNG** [comment] 2014-04-21 18:49
This seems to be the known wifi drop issue, and I think nothing can be done to fix it. 1 year has passed and we haven't found any solution yet :(

**Comment by giraldillo** [comment] 2014-04-22 08:16
ok, to make things as simple as possible I uninstalled all VoIP-Software and used only the built-in VoIP client. 
- System: cm-11.0-20140320-NIGHTLY-LegacyXperia-smultron.zip with original /system/etc/audio_policy.conf (70 lines of code)
- VoIP-Server: A Fritzbox Router with incl. VoIP-support on internal WLAN network, obviously running without any other problems and working with internal VoIP client of stock 4.0.4. (Smartphone ist *_620 and other internal phone (standard DECT phone directly connected to the Fritzbox phone port) is *_1@192.168.0.2 )

Incoming: phone rings, able to connect but no sound (no voice in no direction)
Outgoing: same problem.

Logs (I used catlog, hope that's ok): https://dl.dropboxusercontent.com/u/90369720/incoming.log.txt and https://dl.dropboxusercontent.com/u/90369720/outgoing.log.txt

(Footnote: I experimented also with CSipSimple and audio_policy.conf from here  https://github.com/LegacyXperia/android_device_semc_msm7x30-common/blob/cm-11.0/rootdir/system/etc/audio_policy.conf#L40 But with the effect that immediately after answering a call wifi breaks, 3G connects and breaks only secondes later, too. I'm not sure if this is because of CSipSimple or the changed conf)

(Second FN: with BT headset same problem: Can here the ringtone in headset but after answering there is no sound on both sides. When I disconnect the call on the smartphone side I hear the typical 'click' sound for ended calls from Android; there is also no change when I try to enable the internal speakers.)

**Comment by maystar** [comment] 2014-04-29 14:33
Hello mikeNG,
Do you mean the issue #97? It seems to me that it haven't got so much attention yet. Is the wifi driver closed source? Or why are you so pessimistic regarding this bug? 
I think when there is a general wifi issue, many users must be affected or there must be a configuration which solves it. If the latter is the case, I'm really interested in finding that configuration.

**Comment by mikeNG** [comment] 2014-04-29 14:37
@maystar everything about wifi is open source except the wifi firmware.
Yes, I meant issue #97. This issue had the most attention of all the bugs since cm-10.1. At least 5 people looked into it for months without finding a solution. If you want to go down the rabbit hole, fine, but I don't have the motivation to work on it anymore since it's nearly impossible to fix.

**Comment by MardonHH** [comment] 2014-04-30 00:38
http://www.integrity-project.com/solving-a-wireless-driver-firmware-suspend-resume-issue/

**Comment by giraldillo** [comment] 2014-05-13 07:17
FYI: I need a working SIP client so I switched back to Stock ICS

**Comment by GTNeo** [comment] 2014-07-04 07:13
based on my post
http://forum.xda-developers.com/showthread.php?p=53381758#post53381758

Can someone confirm that the "SIP-WiFi-Problem" depends on hardware of AccessPoint too?

**Comment by mikeNG** [comment] 2014-07-08 10:14
Closing as duplicate of #97

**Closed as completed by mikeNG** 2014-07-08 10:14 UTC
Labels: invalid
