### ISSUE TITLE
(cm11.0) Freezing base internet app

### ISSUE THREAD

**Issue by Xematos** [LegacyXperia/local_manifests#174] opened 2013-11-28 06:54 UTC
Base internet app freez for a second while scrolling a website. Same for Opera.

**Comment by zxcvbnnm** [comment] 2013-11-28 07:27
The same problem here. I try with stock internet app and Dolphin.

**Comment by FernandoUFS** [comment] 2013-11-29 14:57
The same problem here [2]

**Comment by LillyWho** [comment] 2013-12-01 12:20
List of working Browsers [coconut]

Android Browser: works but with freeze and lags sometimes
Firefox: white screen, seems that is doesn't start
Firefox beta: same
Chrome: works but sometimes freeze and empty site after using another app

**Comment by mikeNG** [comment] 2013-12-01 13:26
Duplicate of #181

**Closed as completed by mikeNG** 2013-12-01 13:26 UTC
