### ISSUE TITLE
Superuser on mango does't work

### ISSUE THREAD

**Issue by auhil** [LegacyXperia/local_manifests#16] opened 2013-08-17 08:39 UTC
Build CM10.2-20130809

**Comment by avinashrocks1990** [comment] 2013-08-17 09:07
superuser works 
just change go to developer options and change the root access to "Apps and ADB"

close the thread

**Comment by mikeNG** [comment] 2013-08-17 11:05
Duplicate of #7

**Closed as completed by mikeNG** 2013-08-17 11:05 UTC
