### ISSUE TITLE
cm-11.0-20131211-LX-NIGHTLY-haida camera recording not working

### ISSUE THREAD

**Issue by Jithug** [LegacyXperia/local_manifests#277] opened 2013-12-12 16:48 UTC
cm-11.0-20131211-LX-NIGHTLY-haida camera recording not working.gets stuck up while using them.please improve recording with hd and sd

**Comment by mikeNG** [comment] 2013-12-12 19:32
Duplicate of #267

**Closed as completed by mikeNG** 2013-12-12 19:32 UTC
