### ISSUE TITLE
anzu cm10.2 google services bug - high battery drain, location (gps) is far off from current location

### ISSUE THREAD

**Issue by godofdeath95** [LegacyXperia/local_manifests#46] opened 2013-09-01 18:02 UTC
on top of the already mentioned bugs, there is also the problem with cyanogenmod account connecting to the device - it takes an infinitely long time and still manages not to connect.

This is on the latest cm10.2 update - 20130828
I cant seem to create logcats, any instructions on making them would be great :)

**Comment by gbkreddy1** [comment] 2013-09-02 05:42
Team, First of all thank you very much for the wonderful application and software. Really like it!!  Installed 4.3 with CM 10.2 LX. I have this problem of high battery drain 10% per hour even without using the phone. Please let us know if there is any patch is available for the same. Also, the phone seems to hang / switch off automatically sometimes. Please help!! Thanks again.

**Comment by djey47** [comment] 2013-09-02 07:22
The same here. 
Responsible of battery drain is Google Services, it prevents phone from going into deep sleep even at night with flight mode. Causes between 50 and 65 % battery usage :(

Device: haida
Version : cm10.2 - 20130828

**Comment by DanielMalmgren** [comment] 2013-09-02 08:01
Could you all please search in the forum threads first. This has been discussed several times. What you need to do is add another line into /system/bin/otablock as described here: http://review.cyanogenmod.org/#/c/49329/3/prebuilt/common/bin/otablock.

**Comment by djey47** [comment] 2013-09-02 08:49
Ok, thanks. I had a search before posting for sure, but there are too many results on the forums as Google Services drain is a real issue for most handsets. And not one solution for the same issue. Anyway. 

I'll try this and report.

**Comment by gbkreddy1** [comment] 2013-09-02 10:12
Thank you Daniel. I did search earlier but not sure if this was taken care or not and saw that this defect is open for this version. 

Changed this file now, will monitor it and respond back. 

Thanks again, Have a great day!

**Comment by Gary733** [comment] 2013-09-03 06:24
"location (gps) is far off from current location"
This is caused by wlan access points, which the device can still see ,if they are not anymore in range.
Turn off Network Location to fix this.

**Comment by Gary733** [comment] 2013-09-03 07:58
You can try this gmscore.apk to avoid the Battery drain caused by the google play services.
http://d-h.st/udG
It's an older version.

**Comment by djey47** [comment] 2013-09-03 08:11
Concerning battery drain, change in otablock file can be performed by flashing this zip file: http://forum.xda-developers.com/showpost.php?p=45107951

On my device, 3% battery drain in 6 hours (while I was sleeping, phone in flight mode), that's much better  :)  
I haven't turned wi-fi on since then.

Thanks.

Edit: drain is back, but this time caused by 'Android OS' module. This happened after turning data (2G) on.
A reboot does fix the issue, temporarily.

**Comment by mikeNG** [comment] 2013-09-07 21:34
Please open seperate bug tickets for each bug so we can close it when it's fixed.
Google services battery drain will be fixed in next release

**Closed as completed by mikeNG** 2013-09-07 21:34 UTC

**Comment by godofdeath95** [comment] 2013-09-07 23:29
Yes Sir and thank you.
