### ISSUE TITLE
charging or charging indicator bug

### ISSUE THREAD

**Issue by Nikhildangui** [LegacyXperia/local_manifests#441] opened 2014-02-04 13:05 UTC
I observed that in latest  nightly 21012014 
1) i was on skype voice call and phone was charging simultaneously, phone charged until around 64% and then stop charging showing no progress. Then I restarted the phone and continued charging from 65%  and it could  reached 100% 

2)again while charing i was using the phone, and then kept it idle.
it was put on charge at 12:00 am and till 5:00am (overnight) it was charged untill 78% only.
then i restarted then phone and the indicator showed 100%

ill like to tel you that during 1st scenario i was using new battery which i brought 4 days back, and in 2nd case i was using old battery which is pretty good and still gives 8 hours of heavy usage backup while new battery provides 11Hours backup

This is not the major issue but thought of reporting as it may damage the battery or phone charging capacity if it keep on supplying current to the batteru

Thanks 

battery log screen shot attached, and log attached in second post
![screenshot_2014-02-04-18-32-37](https://f.cloud.github.com/assets/6098030/2076344/99fa4a50-8d9f-11e3-8f34-a133642e7258.png)

**Comment by Nikhildangui** [comment] 2014-02-04 13:31
http://pastebin.com/2TNPxc3r    kmsg log

http://pastebin.com/Psar8w8m  logcat

http://pastebin.com/S168sh2e   radio log

system
Device: 11-20140122-UNOFFICIAL-LegacyXperia-haida
Kernel: 3.4.77-nAa+ mike@buildbot #1

**Comment by Nikhildangui** [comment] 2014-02-05 08:26
Mike one more thing... when my battery was stuck at 78% i think it was continuously supplied with power to charge and it actually charged properly and it last me whole day.. but now when it charged properly without any issue or getting charging stuck, the battery last much lesser, inspite lesser usage of phone and lesser whatsapp
i think some changes are needed in kernal or rom for proper charging,

i am nt developer just a user so if  i am wrong and troubling u then sorry mike,

i have installed du battery saver app lets see if it can properly charge my battery

**Comment by mikeNG** [comment] 2014-02-05 09:22
I will try to reproduce it but I never had such problems so far...

**Comment by Nikhildangui** [comment] 2014-02-05 10:37
I don't think it can be reproduce...  Becoz I faces that problem only twice... 
But my main concern is that this can be reason for battery drain few ppl reported,  as actually its not battery drain but battery not charging... 
Let me elaborate 
When  I had stock rom I saw that even after battery was charged 100 %  it used to still supplied with current for another 15 mon or so... 
But I dint saw same with your kernal...  
And it stops charging as soon as it touches 100%... 
I feels so I may be wrong sir
Thanks

**Comment by mikeNG** [comment] 2014-02-12 15:31
I'm closing this since it's very hard to reproduce and there is very little info in the logs.

I couldn't reproduce in any of my 3 phones testing all week.

No worries about the battery, it can't be overcharged, the chip will limit the power supply in all circumstances.

**Closed as completed by mikeNG** 2014-02-12 15:31 UTC
