### ISSUE TITLE
video recording still not working in cm11..build4

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#347] opened 2013-12-26 08:21 UTC
video recording not working in mt15i

**Comment by nonphanu** [comment] 2013-12-26 08:37
me too arc s

**Comment by ghost** [comment] 2013-12-26 08:46
Yes.. It is not working for LWW WT19i

**Comment by c3pr3u** [comment] 2013-12-26 11:40
for st15i too

**Comment by mikeNG** [comment] 2013-12-26 13:29
Why do you need to open a seperate issue when there is already one open!!???
Duplicate of #267

**Closed as completed by mikeNG** 2013-12-26 13:29 UTC
