### ISSUE TITLE
[CM11] Xparia Arc (anzu) no mount function

### ISSUE THREAD

**Issue by geosone** [LegacyXperia/local_manifests#477] opened 2014-02-12 06:52 UTC
The CW recovery has a problem to mount the sd-card as usb device that can then be used as a usbstick by the wks

**Comment by sidharthgtm** [comment] 2014-02-12 07:42
[CM11][SMULTRON] Recovery Unable to mount USB storage

recovery log : 

http://pastebin.com/m7wLhLP0

**Comment by mikeNG** [comment] 2014-02-12 15:18
You are on windows? If yes, it's a driver problem, search xda LX threads for the solution.

**Comment by geosone** [comment] 2014-02-14 10:38
i don't think because it is working with 10.1 and 10.2 but not with 11.0 but i will check

**Comment by tjcomserv** [comment] 2014-02-19 09:53
I had a similar problem, removing all related drivers and then downloading the latest version of flashtool and reinstalling drivers solved the issue (don't forget to reboot into "Disable Driver signature Enforcement" mode if using Windows 8)

**Comment by ghost** [comment] 2014-03-04 21:42
Hehe, @mikeNG  okay I just did jump on the CM11 train and the problem is quite similar to the issue on CM10.2, some of us (including me) were having.

See - https://github.com/LegacyXperia/local_manifests/issues/33#issuecomment-31377723

The fix seems a bit more complicated, because atleast I was having problems mounting mass storage under Win 7 64bit even on Android in addition to CWM. I eventually got everything to work after playing with the USB connection modes and manually changing the drivers in the device manager.

I will have to uninstall all my drivers to reproduce it again to be able to get a guide up. I will do this later this week as I have some other stuff to work at.

~skaa

**Comment by ghost** [comment] 2014-03-04 22:35
changing Android ADB Interface to a composite device in the device manager installs a sony sa0102 driver, changing this sony sa0102 into a mass storage device, enables mounting mass storage in CWM. However mounting mass storage when usb debugging is active in android won't work. Mounting mass storage when unchecking usb debugging works without problems.

Take this with a grain of salt.

**Comment by mikeNG** [comment] 2014-03-10 12:21
Please upload the drivers you're using somewhere so I can take a look. In linux (which is my everyday OS) everything works perfectly in the past 10 months, the issue is in the windows drivers.

**Comment by ghost** [comment] 2014-03-11 23:59
Here you go:
https://www.dropbox.com/s/dqdn6kky9aqjy6c/Drivers.zip

I haven't installed anything else beside the Sony PC companion, update center, google drivers from android sdk and the driver from flashtool and fastboot. All I did were the two changes I mentioned above and the rest got set up automatically. 

Linux is the smarter OS. Perhaps Windows does not like some definition in the USB descriptor and sets up the wrong drivers by default.  The reason why some people do experience this and some do not may be because as far as I know the first time a device driver gets installed a registry key entry that maps the device ID to the driver is set up. So even if something messes up later the setting is already stored inside windows ... unless it's a first  time install.

I did pull from the repository a few weeks ago but comming from my 2-3project developments to CM overwhelmend me. I will take a look the next few days maybe I find something. But well you are the expert and I might be just totally wrong.

**Comment by ghost** [comment] 2014-03-14 10:19
@mikeNG I have been browsing through the official CM11 changelog and found something that may be related. This commit is for a samsung device but basically they swapped the adb and mass_storage order in recovery, see here:

http://review.cyanogenmod.org/#/c/60715/

When I did set up manually the drivers in the device manager I pretty much did swap out the ADB driver for a Mass_storage one. See above my 2nd post.

**Comment by mikeNG** [comment] 2014-03-17 19:09
There will be some changes included in the next cm11 build that might be related to this issue.

**Comment by sidharthgtm** [comment] 2014-03-27 12:49
Fixed in latest build !

**Closed as completed** 2014-04-02 13:56 UTC
Labels: cannotreproduce
