### ISSUE TITLE
[CM11] 2014-09-07 Bluetooth headsets / car kit semi-work

### ISSUE THREAD

**Issue by xange** [LegacyXperia/local_manifests#789] opened 2014-09-12 12:27 UTC
logs: https://gist.github.com/xange/27c895993cd1e8340d7b
tested on my bluetooth headset MW600 and my car's DVD player with bluetooth feature, both having the same results: when start playing 1st song using apollo, everything works fine (i have no idea about the DSP reporting the sound enhancement doesn't work because I didn't pay attention to the audio quality), the moment it finish the 1st song, then logs keep on spam with debug info untill i close the bluetooth connection.

**Comment by mikeNG** [comment] 2014-09-12 12:42
So this happens on a clean build without mods?

**Comment by xange** [comment] 2014-09-12 13:28
sorry, i took another test on selfbuild 20140911 (1st build no mods, only the commit 72658, maybe it was related to the 3 cherries you removed) just now works fine. where 0907 rom still have those 3 patch in it where is saw people report not working in Q&A just now. 
And about the DSP error, it happen randomly (sometimes work, sometimes don't), since the hw mp3 decoding patch, perhaps.
I'll give another report after testing with aac audio.

**Comment by xange** [comment] 2014-09-12 13:35
speaks of the witch, the same error happened right now.... i see my logcat in term is spamming just like the logs in above, with the same song "where no one goes"..... and yup, turn off bluetooth will stop the spamming.
add: right after turn off bluetooth, i resume the music from the notification tray, and the errors keep spams the logs now and no music is being play.
another add: i notice it spams the logs from:
E/MediaPlayer( 3914): Should have subtitle controller already set
I/ExtendedUtils( 4444): AV Sync late margin : Intended=40ms Using=0ms... untill
W/MediaPlayer( 3914): mediaplayer went away with unhandled events

just 1 thing caught my eyes, "media server has died" ; had to long press back button to force close apollo for now.

**Comment by xange** [comment] 2014-09-12 14:17
10 minutes test on aac file music, so far its okay, just while playing the aac music, the logs too is being spammed with info, possible to disable it?
about playing mp3 files untill have that error, conclusion is, it doesn't happen on all mp3 files, only certain after i test and random pick, if i pick again the same song that gives the error, the error persist, while those that didn't, will play without error. I'll reboot my phone now and test again those mp3 that gives error and reply later

**Comment by xange** [comment] 2014-09-12 14:33
after reboot even worst, same thing happen as in 1st report, 1st song was okay, before the 2nd song being play, the phone goes hard reboot.
last kmsg: https://gist.github.com/xange/76e5861e6328055f529b

**Comment by xange** [comment] 2014-09-12 15:17
later i'll make another clean build overnight to test the bluetooth, i'll start testing this with remove the omx mp3 hw decoder and see how it goes, because I only have this issue since 0907 builds where this commit is applied.

**Comment by xange** [comment] 2014-09-13 02:19
@mikeNG as expected, i tested on another clean build (0913) without hw mp3 decoder, bluetooth issue dissappeared.... its need some fix for bluetooth before it merge into cm... please request others to test on this 1st to confirm. 
procedure: remove cherry pick from updates.sh -> delete hardware/qcom/media-caf folder -> repo sync -> run updates.sh -> build

**Comment by rtammekivi** [comment] 2014-09-13 09:53
The hard reboot issue is pretty much the same as the hard reboot caused by Viber. It's fixed right now in the kernel source.

However the other issue with OMX state is very rare. When we were bringing it up I experienced same error when playing network stream but it has not happened since.

**Comment by xange** [comment] 2014-09-13 10:49
when was it fixed? i mean the Viber crashed. because the latest selfbuild I made was dated 13th sep 12.51am MYT (+8.00). I'd no idea if the fix is already sync-ed into my source here that effect my test here.
If the fix was in kernel, I tested the ROM with 2 kernel by mistake: 0913(maybe contain that viber fix) and 0911(pretty sure it does not have the viber fix), both gave me the same result with the 0913 ROM (no hw mp3 decoder). so my conclusion is the viber crash is differ from this, am I right? although they looks alike.

**Comment by ghost** [comment] 2014-10-02 12:20
@xange was this issue fixed for you?

**Comment by xange** [comment] 2014-10-03 08:23
I can no longer self build for test until I settle my university stuff 1st. The last self build I made was 19092014. Without HW mp3 decode.

**Comment by xange** [comment] 2014-10-03 12:05
@Skaveelicious which commit you see that will fix this problem anyway?

**Comment by ghost** [comment] 2014-10-03 15:51
@xange I was asking because a qdsp5v2 fix was merged a while ago and I have been testing the latest source changes for the past few days including bluetooth playback and could not find any issue.

For the BT test I paired my Arc S with my Notebook and have been listening to music for about 3h so far and have not yet had any problems. Both, Poweramp and Apollo. DPS Manager works also. 

Bellow I'm attaching a snipped of how my log looks like when I play via BT, you can see `AudioFocus` being called twice. Those were the times when one track transitionend to the new one.

```
[ 10-03 17:35:14.763  4166: 4166 D/MtpService ]
updating state; isCurrentUser=true, mMtpLocked=true

[ 10-03 17:35:41.829   594:  675 I/PowerManagerService ]
Going to sleep due to screen timeout...

[ 10-03 17:35:42.320   228:  228 D/SurfaceFlinger ]
Screen released, type=0 flinger=0x1b944e0

[ 10-03 17:35:42.340   228:  228 D/qdhwcomposer ]
hwc_blank: Blanking display: 0

[ 10-03 17:35:42.610   228:  228 D/qdhwcomposer ]
hwc_blank: Done blanking display: 0

[ 10-03 17:35:43.051   594:  712 D/PowerManagerService-JNI ]
Excessive delay in autosuspend_enable() while turning screen off: 4726ms

[ 10-03 17:35:43.461   704:  704 W/View     ]
requestLayout() improperly called by android.widget.TextClock{42132e28 V.ED..........ID 0,0-106,129 #7f0b0013 app:id/clock1_regular} during layout: running second layout pass

[ 10-03 17:35:43.461   704:  704 W/View     ]
requestLayout() improperly called by android.widget.TextClock{41e43560 V.ED..........ID 106,0-229,129 #7f0b0014 app:id/clock2_regular} during layout: running second layout pass

[ 10-03 17:35:43.461   704:  704 W/View     ]
requestLayout() improperly called by android.widget.TextClock{4207aa30 V.ED..........ID 134,0-245,25 #7f0b0018 app:id/date_bold} during layout: running second layout pass

[ 10-03 17:35:43.531   238:  406 I/audio_a2dp_hw ]
adev_set_parameters: state 1

[ 10-03 17:35:43.531   238:  406 I/audio_a2dp_hw ]
out_set_parameters: state 1

[ 10-03 17:35:43.531   238:  406 I/str_params ]
key: 'screen_state' value: 'off'

[ 10-03 17:35:43.531   794:  794 I/wpa_supplicant ]
wpa_driver_nl80211_driver_cmd: Unsupported command SETSUSPENDMODE 1

[ 10-03 17:36:54.350   594:  917 I/MediaFocusControl ]
 AudioFocus  requestAudioFocus() from android.media.AudioManager@41daa160com.maxmpz.audioplayer.player.PlayerService$20@41da86c0

[ 10-03 17:36:54.550   594:  916 I/MediaFocusControl ]
  Remote Control   registerMediaButtonIntent() for PendingIntent{421ec5c8: PendingIntentRecord{42288580 com.maxmpz.audioplayer broadcastIntent}}

[ 10-03 17:39:01.304   794:  794 I/wpa_supplicant ]
wlan0: CTRL-EVENT-SCAN-STARTED

[ 10-03 17:39:03.546   813: 1579 I/GCoreUlr ]
Successfully inserted location

[ 10-03 17:39:03.546   813: 1579 I/GCoreUlr ]
Not calling LocationReportingService, hasMoved: false, elapsed millis: 3111110,request: Phone

[ 10-03 17:40:37.168   794:  794 I/wpa_supplicant ]
wlan0: WPA: Group rekeying completed with bc:05:43:d7:3c:4e [GTK=TKIP]

[ 10-03 17:41:10.140   594:  916 I/MediaFocusControl ]
 AudioFocus  requestAudioFocus() from android.media.AudioManager@41daa160com.maxmpz.audioplayer.player.PlayerService$20@41da86c0

[ 10-03 17:41:10.250   238:  698 D/AudioFlinger ]
pause(4098), calling pid 3757

[ 10-03 17:41:10.250   594:  892 I/MediaFocusControl ]
  Remote Control   registerMediaButtonIntent() for PendingIntent{41e57e70: PendingIntentRecord{42288580 com.maxmpz.audioplayer broadcastIntent}}

[ 10-03 17:41:10.260   238:  238 D/AudioFlinger ]
start(4097), calling pid 3757 session 12

[ 10-03 17:41:10.260   238:  238 D/AudioFlinger ]
? => ACTIVE (4097) on thread 0xec6928
```

**Comment by xange** [comment] 2014-10-04 11:52
i'll back on testing maybe next week... because i had removed VM on my PC, and i'm going to multi-boot in my new laptop since VM really make me suffocate with the building time @.@ if this is fix in your opinion, tag me or mike to close this issue then.
add: mind to give the URL and point me the commit?

**Comment by rtammekivi** [comment] 2014-10-05 16:09
It should be this one: https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commit/0a9c8ac8e679ff42e139fa4539ce283f9708549b

**Comment by mikeNG** [comment] 2014-10-06 22:53
Should be fixed in latest build

**Closed as completed by mikeNG** 2014-10-06 22:53 UTC

**Comment by xange** [comment] 2014-10-07 13:49
FYI: yup. really fixed. thanks.
