### ISSUE TITLE
Wifi apps always scanning

### ISSUE THREAD

**Issue by jlmcr87** [LegacyXperia/local_manifests#34] opened 2013-08-28 13:27 UTC
When wifi is enabled and I open Router keygen or penetrate pro for example, it doesn´t detect any network, always shows scanning......... If I enter this apps with wifi off (and the app auto enable wifi), they works. Can you take a look on that? Thanks

**Comment by mikeNG** [comment] 2013-09-10 02:01
Wait for next release and report back

**Comment by jlmcr87** [comment] 2013-09-18 14:20
Mike same problem with 20130918 build on Anzu

**Comment by jlmcr87** [comment] 2013-09-18 18:59
![screenshot_2013-09-18-20-54-06](https://f.cloud.github.com/assets/4967467/1167775/7616dcd4-2094-11e3-8408-99125d0c889a.png)
![screenshot_2013-09-18-20-54-31](https://f.cloud.github.com/assets/4967467/1167776/77b31e36-2094-11e3-8ae3-3c3fa1272f5c.png)

**Comment by mikeNG** [comment] 2013-09-19 12:23
Is this present only in 10.2?
Maybe there's a fix for it but I haven't tried it: http://review.cyanogenmod.org/50505

**Comment by jlmcr87** [comment] 2013-09-19 12:26
Yes only in CM 10.2. In CM10.1 it´s OK

**Comment by avelos156** [comment] 2013-09-20 10:04
Same for me here ([anzu][cm10.2-20130918]). That was also happening in the previous nightly build of CM10.2.

In fact, no application can see and monitor the wi-fi. I have tried several ones. If you turn on the wi-fi while running "wifi analyzer" for example, it will show you some information but it stops there, there is no active monitoring of the wireless environment. All apps are doing the same thing. Could it be something related to permissions..?

**Comment by mikeNG** [comment] 2013-09-20 12:50
Duplicate of #22

**Closed as completed by mikeNG** 2013-09-20 12:50 UTC
