### ISSUE TITLE
Settings/Buttons stops

### ISSUE THREAD

**Issue by tomasz89** [LegacyXperia/local_manifests#91] opened 2013-10-14 02:51 UTC
On a Sony Xperia Arc S, running cm-10.2_anzu-LX-20131001-NIGHTLY.

When I access Settings/Buttons, I get an immediate error message:
Unfortunately, Settings has stopped.

**Comment by mikeNG** [comment] 2013-10-14 02:58
Duplicate of #77

**Closed as completed by mikeNG** 2013-10-14 02:58 UTC
