### ISSUE TITLE
[10.2] [coconut] WIFI interrupts wl12xx: ERROR watchdog interrupt received! starting recovery.

### ISSUE THREAD

**Issue by Institor666** [LegacyXperia/local_manifests#189] opened 2013-11-28 23:59 UTC
As I described in https://github.com/LegacyXperia/local_manifests/issues/113, SIP (VoIP) via wifi on CM 10-10.2 (20131112) not working. log (dmesg) contains many of

```
<3>[  119.435485] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[  119.435791] wl12xx: Reading FW panic log
<6>[  119.436279] wl12xx: Hardware recovery in progress. FW ver: Rev 6.5.7.0.46
<6>[  119.436553] wl12xx: pc: 0x238
<6>[  119.436798] wl12xx: removing interface 84:00:d2:fb:87:28
<6>[  119.437042] wl12xx: removing interface 84:00:d2:fb:87:27
<6>[  119.441741] ieee80211 phy0: Hardware restart was requested
<6>[  119.443908] wl12xx: state: 0
<3>[  119.452087] [audio_pcm_in.c:audpcm_in_enc_config] sending AUDPREPROC_AUDREC_CMD_ENC_CFG command
<3>[  119.464691] [audio_acdb.c:acdb_fill_audpreproc_fluence] error in finding fluence block
<3>[  119.465148] [audio_acdb.c:acdb_calibrate_audpreproc] fluence block is not found
<6>[  120.175689] wl12xx: firmware booted (Rev 6.3.10.0.136)
<6>[  120.181060] wl12xx: state: 2
<6>[  120.181427] wl12xx: adding p2p mgmt vif
<6>[  120.223663] wl12xx: Association completed.
<3>[  120.247131] wl12xx: ERROR no active RX BA session on tid: 0
<7>[  120.247375] HW problem - can not stop rx aggregation for tid 0
<3>[  120.253875] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[  120.254241] wl12xx: Reading FW panic log
<6>[  120.254638] wl12xx: Hardware recovery in progress. FW ver: Rev 6.3.10.0.136
<6>[  120.255004] wl12xx: pc: 0x4bc
<6>[  120.255187] wl12xx: removing interface 84:00:d2:fb:87:28
<6>[  120.255493] wl12xx: removing interface 84:00:d2:fb:87:27
<6>[  120.261901] ieee80211 phy0: Hardware restart was requested
<6>[  120.266113] wl12xx: state: 0
<6>[  120.975952] wl12xx: firmware booted (Rev 6.3.10.0.136)
<6>[  120.981140] wl12xx: state: 2
<6>[  120.981292] wl12xx: adding p2p mgmt vif
<6>[  121.023620] wl12xx: Association completed.
<3>[  121.052612] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[  121.053009] wl12xx: Reading FW panic log
<6>[  121.053375] wl12xx: Hardware recovery in progress. FW ver: Rev 6.3.10.0.136
<6>[  121.054046] wl12xx: pc: 0x4bc
<6>[  121.054229] wl12xx: removing interface 84:00:d2:fb:87:28
<6>[  121.054565] wl12xx: removing interface 84:00:d2:fb:87:27
<6>[  121.058685] ieee80211 phy0: Hardware restart was requested
```

etc.

This affects not only sip, wifi drops randomly resulting speed decreasing and sometimes disconnections.
I found: http://forum.xda-developers.com/showthread.php?p=41538206#post41538206
and http://e2e.ti.com/support/low_power_rf/f/307/t/263908.aspx?pi267162=1
and http://connectivity198.rssing.com/chan-4845084/all_p274.html
Looks like problem with wl12xx firmware.

**Comment by mikeNG** [comment] 2013-12-01 13:23
Duplicate of #97

**Closed as completed by mikeNG** 2013-12-01 13:23 UTC
