### ISSUE TITLE
[CM11][20150406][urushi] back/menu button not working

### ISSUE THREAD

**Issue by sidelarge** [LegacyXperia/local_manifests#906] opened 2015-04-10 15:03 UTC
Back and Menu buttons (capacitive) stopped working altogether with the latest nightly CM11.  Only the Home key (hard) does.

**Comment by azakosath** [comment] 2015-04-14 10:35
Duplicate of #349 maybe?

**Closed as completed** 2015-04-15 15:23 UTC

**Comment by HanruiWang** [comment] 2015-06-01 11:50
Mebey you delete The last shurufa.
