### ISSUE TITLE
Neo V - screen not turn of while voice call

### ISSUE THREAD

**Issue by huseyinzengin** [LegacyXperia/local_manifests#337] opened 2013-12-25 13:54 UTC
Hi,
in voice call screen keeps on, earing touch any screen an open setting etc. How can I control sensor on latest nightly rom?

Rom : 
cm-11.0-20131211-LX-NIGHTLY-haida

**Comment by mikeNG** [comment] 2014-01-11 20:33
duplicate of #299

**Closed as completed by mikeNG** 2014-01-11 20:33 UTC
