### ISSUE TITLE
[CM11-20131127-UNOFFICIAL-hallon] music distortion 

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#230] opened 2013-12-04 23:21 UTC
music gets distorted in Play Music app when locking and unlocking the screen. it's possible that this bug also affects other music players, i haven't checked.

**Comment by mikeNG** [comment] 2013-12-04 23:28
Duplicate of #180

**Closed as completed by mikeNG** 2013-12-04 23:28 UTC
