### ISSUE TITLE
status bar not transparent [cm11]

### ISSUE THREAD

**Issue by taha001** [LegacyXperia/local_manifests#214] opened 2013-12-03 05:57 UTC
Status bar not transparent unlike kitkat 4.4 features it

**Comment by nefelim4ag** [comment] 2013-12-03 07:56
https://github.com/LegacyXperia/local_manifests/issues/183
This is not a bug, close issue

**Comment by taha001** [comment] 2013-12-03 08:14
but in kitkat4.4 it has to be transparent...right bro?

**Comment by djey47** [comment] 2013-12-03 12:00
-> with low RAM setting in build.prop -> not transparent.
-> without low RAM setting -> transparent.

Those are the features.

**Comment by mikeNG** [comment] 2013-12-03 15:52
Duplicate of #183

Why nobody checks for already open issues?!!!!!!

**Closed as completed by mikeNG** 2013-12-03 15:52 UTC
