### ISSUE TITLE
[10.2] Deep Sleep & Android OS abnormality!

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#113] opened 2013-10-28 05:38 UTC
Last night I left my phone with a 95% of charge but this morning, I checked it and wtf, it's only 17% of the power left! 
The only reason I saw is the Android OS been gone crazy running the whole night and keeping Deep Sleep mode deactivated :( 
![screenshot_2013-10-28-11-39-30](https://f.cloud.github.com/assets/5206764/1417575/5c8ee50a-3f92-11e3-849d-e156d72cf9bc.png)
![screenshot_2013-10-28-11-44-37](https://f.cloud.github.com/assets/5206764/1417574/5c7b97b6-3f92-11e3-8f44-ae315ee13a89.png)
![screenshot_2013-10-28-11-39-22](https://f.cloud.github.com/assets/5206764/1417576/5cb2380c-3f92-11e3-8d69-53b8651e1657.png)

**Comment by the-dreamer** [comment] 2013-10-28 08:01
I see gps was on. This seems to be a bug on all cm images i had on my ray. I think that will never be solved. i had this bug on CM 10 / 10.1 and now also on 10.2 ..... I use GPS only if it is really necessary (google nav for example). After usage i do a reboot to prevent battery drain...

**Comment by JovieBrett** [comment] 2013-10-29 09:26
But I did not leave my GPS on for a long time. I turned it off before I sleep that night. There are also users experiencing this problem.

**Comment by the-dreamer** [comment] 2013-10-29 09:41
Yes, this is the bug! Once enabled something is preventing the device to go into the sleep and drain the battery. As i have written a reboot is the only solution so far!

**Comment by JovieBrett** [comment] 2013-10-30 06:53
Ok, thanks! Last night before I went to sleep, I rebooted my phone to make sure anything will be alright :-)
That's the solution for now but I hope there is a right fixes for this :-D

**Comment by enveraltin** [comment] 2013-10-30 12:36
I have the same problem on 20131013-nightly with a Mango/XperiaMiniPro. Do any of you have Bluetooth on?

I turned off everything and rebooted the phone. Then started turning on things one-by-one and waited enough to see what's killing it. It seems like Bluetooth was the offender.

I tried to browse through Git logs to see what's changed between 20131013 and 20131024 but only found BLE was enabled for XperiaMiniPro. I tried upgrading, but com.android.phone was force-closed even after a wipe, so I restored back to 20131013. I see boot.img has the same size, so I didn't flash it before upgrading.

Can't use my phone without bluetooth, and it can survive for 6 hours only on battery. I'd be happy to help debug this.

**Comment by mikeNG** [comment] 2013-10-30 13:37
You ALWAYS have to flash the kernel

**Comment by enveraltin** [comment] 2013-10-30 15:01
Thanks a lot.

I did, and 20121024 solved Bluetooth wakelock problem.

**Comment by JovieBrett** [comment] 2013-10-31 06:35
Thanks @mikeNG 
Anyway I want to report something about Bluetooth, since I haven't got any logcats about this problem, I'll just leave a comment here.
When I'm using bluetooth when Wifi is on, bluetooth doesn't work properly. I tried to send a file via bluetooth with Wifi currently turned on but the file is not sending. When I turned the Wifi off and try to send the file, the file sent successfully. Wifi interrupts with Bluetooth when it  is turned on.

**Comment by ghost** [comment] 2013-11-02 15:12
I also see the high battery drain from 'Android OS' with 20121101 on a mango.
In my case I think it is caused by the wifi appearing to constantly report state changes.
See the logcat:

I/PowerManagerService(  556): Going to sleep due to screen timeout...
E/        (  556): sensors_sysfs_write: open failed! -1
E/DASH - bma250_input(  556): bma250_input_set_delay: sysfs.write_int failed!
D/LightsService(  556): Excessive delay setting light: 73ms
V/KeyguardHostView(  556): Keyguard widgets disabled by DPM
V/KeyguardHostView(  556): Keyguard secure camera disabled by DPM
D/SurfaceFlinger(  233): Screen released, type=0 flinger=0x8e4478
V/KeyguardHostView(  556): hide transport, gen:1
V/KeyguardHostView(  556): music state changed: 0
D/SurfaceControl(  556): Excessive delay in blankDisplay() while turning screen off: 462ms
D/PhoneApp(  798): mReceiver: ACTION_SCREEN_OFF / ACTION_SCREEN_ON
D/AccelerometerListener(  798): enable(false)
I/wpa_supplicant( 2765): p2p0: P2P-FIND-STOPPED 
D/MobileDataStateTracker(  556): default: setPolicyDataEnable(enabled=true)
D/WifiStateMachine(  556): VerifyingLinkState enter
D/WifiStateMachine(  556): VerifyingLinkState GOOD_LINK_DETECTED: transition to captive portal check
D/WifiStateMachine(  556): CaptivePortalCheckState enter
D/ConnectivityService(  556): Captive portal check NetworkInfo: type: WIFI[], state: CONNECTING/CAPTIVE_PORTAL_CHECK, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/WifiStateMachine(  556): CaptivePortalCheckState CMD_CAPTIVE_CHECK_COMPLETE
D/ConnectivityService(  556): handleCaptivePortalTrackerCheck: call captivePortalCheckComplete ni=NetworkInfo: type: WIFI[], state: CONNECTING/CAPTIVE_PORTAL_CHECK, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/ConnectivityService(  556): ConnectivityChange for WIFI: CONNECTED/CONNECTED
V/ReceiverConnectionChanges( 4329): Connection status has changed
D/ConnectivityService(  556): handleConnectivityChange: address are the same reset per doReset linkProperty[1]: resetMask=0
D/Nat464Xlat(  556): requiresClat: netType=1, hasIPv4Address=true
D/MobileDataStateTracker(  556): default: setPolicyDataEnable(enabled=true)
V/ReceiverConnectionChanges( 4329): Connection status has changed
D/MobileDataStateTracker(  556): default: setPolicyDataEnable(enabled=true)
V/ReceiverConnectionChanges( 4329): Connection status has changed
D/ServicePendingActions( 4329): Starting syncing
D/ServicePendingActions( 4329): Starting syncing
D/ServicePendingActions( 4329): Starting syncing
D/ConnectivityService(  556): NetTransition Wakelock for ConnectedState released by timeout
D/Tethering(  556): MasterInitialState.processMessage what=3
D/StatusBar.NetworkController(  654): updateConnectivity: intent=Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 (has extras) }
D/StatusBar.NetworkController(  654): updateConnectivity: networkInfo=NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/StatusBar.NetworkController(  654): updateConnectivity: connectionStatus=0
D/StatusBar.NetworkController(  654): updateConnectivity: intent=Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 (has extras) }
D/StatusBar.NetworkController(  654): updateConnectivity: networkInfo=NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/StatusBar.NetworkController(  654): updateConnectivity: connectionStatus=0
D/CMStats ( 6487): Waiting for next sync : 19 hours
D/TelephonyProvider(  798): Column apn id key is 'apn_id'
D/WeatherUpdateService( 5577): Service started, but shouldn't update ... stopping
D/GCM     (  845): GcmService start Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 cmp=com.google.android.gms/.gcm.GcmService (has extras) } android.net.conn.CONNECTIVITY_CHANGE
V/ReceiverConnectionChanges( 4329): Connection status has changed
D/ServicePendingActions( 4329): Starting syncing
D/TransactionService( 6197): Cursor= >>>>> Dumping cursor android.content.ContentResolver$CursorWrapperInner@41919628
D/TransactionService( 6197): <<<<<
D/TransactionService( 6197): updateTxnRequestStatus servId=1
D/TransactionService( 6197): removeNotification, startId=1
D/ConnectivityService(  556): handleInetConditionHoldEnd: net=1, condition=100, published condition=0
D/StatusBar.NetworkController(  654): updateConnectivity: intent=Intent { act=android.net.conn.INET_CONDITION_ACTION flg=0x8000010 (has extras) }
D/StatusBar.NetworkController(  654): updateConnectivity: networkInfo=NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/StatusBar.NetworkController(  654): updateConnectivity: connectionStatus=100
D/StatusBar.NetworkController(  654): updateConnectivity: intent=Intent { act=android.net.conn.INET_CONDITION_ACTION flg=0x8000010 (has extras) }
D/StatusBar.NetworkController(  654): updateConnectivity: networkInfo=NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/StatusBar.NetworkController(  654): updateConnectivity: connectionStatus=100
D/GCM     (  845): Message class epz
D/ConnectivityService(  556): handleInetConditionHoldEnd: net=1, condition=100, published condition=100
D/StatusBar.NetworkController(  654): updateConnectivity: intent=Intent { act=android.net.conn.INET_CONDITION_ACTION flg=0x8000010 (has extras) }
D/StatusBar.NetworkController(  654): updateConnectivity: networkInfo=NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/StatusBar.NetworkController(  654): updateConnectivity: connectionStatus=100
D/StatusBar.NetworkController(  654): updateConnectivity: intent=Intent { act=android.net.conn.INET_CONDITION_ACTION flg=0x8000010 (has extras) }
D/StatusBar.NetworkController(  654): updateConnectivity: networkInfo=NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "paradisefound", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/StatusBar.NetworkController(  654): updateConnectivity: connectionStatus=100
I/wpa_supplicant( 2765): p2p0: P2P-FIND-STOPPED

**Comment by enveraltin** [comment] 2013-11-02 15:56
Same here, mango.

I turned off network location service and the problem is gone now.

**Comment by ghost** [comment] 2013-11-02 16:25
I already had all the location stuff turned off.
I've now killed the service to see if that makes things any better.

**Comment by ghost** [comment] 2013-11-02 20:05
Killing the location service didn't make any difference.
Still seeing a drain of about 14% an hour. 44% of usage in Android OS.
WakeLock Detector says over 2h in rx_wake.
Can I capture any other logs to help figure this out?

**Comment by ghost** [comment] 2013-11-06 00:35
I think the problem might be to do with the wifi calibration.

In the commit:

https://github.com/LegacyXperia/android_device_semc_mango/commit/f7d32dc5cc2b22539e2b834cb769b71f559a8aed

many of the insertion loss parameters from the default TI file which are in hex are replaced by their decimal equivalents.
I assume these came from an old SEMC file but reading the source of the calibration code they should be hex.
This effectively means we are claiming the the traces on the board have much greater loss.
The last version I had with sensible power consumption was 20131001 which didn't have that commit.

**Comment by ghost** [comment] 2013-11-06 15:33
Change the .ini file to have the values in hex but it didn't help.
Still seeing 10% per hour battery drain compared to 3% on 20131001.

**Comment by mikeNG** [comment] 2013-11-06 16:23
Did you repeat the calibration to make sure the new values were used?

**Comment by ghost** [comment] 2013-11-06 16:40
Yes been caught out by that before but this time I made sure.
I've tried just about everything I can think of now including the slightly newer TI firmware.

I'm begining wonder if something in my network is triggering a bug in the newer versions of the wl12xx drivers.
I am running cisco APs and there's IPv6 but both of those would be hard to change/remove for testing.

**Comment by ghost** [comment] 2013-11-07 11:26
I think I've figured it out.
The wl12xx driver takes a wakelock which is supposed to allow received packets to reach userspace.
The timeout on this wake lock is set at 1 second. But that's based on the CPU speed when the wakelock is taken.
So depending on other power management the wakelock might be too long or too short.
Too long and the phone will stay awake when it doesn't need to.
Too short and the packet may not reach user space before the phone goes into deep sleep.
I suspect I'm seeing it being too short and that causes the wl12xx to think it has stalled.
This seems to be a fundamental flaw in Android power management as the wakelock timeouts are just guesswork.
I think this also explains the issues people sometimes have with SD cards not being detected as the same trick is being used.
I need to get a build system set up so I can build kernels with different values.

**Comment by mikeNG** [comment] 2013-11-07 12:17
You might find some useful changes here http://review.cyanogenmod.org/#/c/52941/

**Comment by ghost** [comment] 2013-11-07 12:57
Thanks. That seems to suggests that the timeout needs to be smaller:

wake_lock_timeout(&wl->rx_wake,HZ/2);

instead of:

wake_lock_timeout(&wl->rx_wake,HZ);

Not what I expected but I'll give that a go first.

They also seem to be ignoring an event which causes an adapter reset.
That's probably a good idea too.

**Comment by ghost** [comment] 2013-11-09 20:49
None of that made any difference :-(
The HTC patches once various bits of debug are stripped out. Boil down to:

1) A tweak to handle an old Apple AP.
2) Cope with loosing ACKs in AP mode.
3) Changes to timeouts on RX and TX.
4) Change the WOW rules for non-unicast
5) Make the timeout on the rx_wake lock 0.5 seconds.
6) Add a wakelock for the card starting up.
7) Changes to how MAC addresses are allocated.

**Comment by mikeNG** [comment] 2013-11-09 20:58
you can try the 4.1.\* changes from here, it's the old 2.6.32 driver: https://github.com/mikeNG/compat-wireless/commits/sony-compat

mind that most of the changes must be reimplemented because the sources have changed

**Comment by ghost** [comment] 2013-11-10 00:09
Before I tried the changes from the old drivers I converted the rx_wake, wakelock from WAKE_LOCK_SUSPEND to WAKE_LOCK_IDLE.
I'm now down to less than 3% drain an hour and 90% deep sleep.
Very simple patch here.

http://pastebin.com/YcbyVNw9

Not really sure why this works.
Maybe my theory about the wake lock being messed up by CPU speed changes was right.

**Comment by ghost** [comment] 2013-11-10 10:22
I've now been running with that patch with the phone idle for 10hrs but wifi on.
Deep sleep 96.5%.
13% battery used ~1.2%/h.
That's about a tenth of the drain I see without it.
Wifi appears to work fine. No stalls in app downloads.

**Comment by JovieBrett** [comment] 2013-11-10 10:34
@stashcroft, can you create a flashable zip for that? I have no knowledge to work on patches :(

**Comment by ghost** [comment] 2013-11-10 10:52
I'm a kernel developer not an Android one.
I made my first build yesterday and I didn't trust it enough to flash it on to my phone.
I expect most of userspace bits would be broken as I've been manually replacing the files in /system/lib/modules.
Better to wait for somebody who knows what they are doing to add it to a test build.

**Comment by JovieBrett** [comment] 2013-11-10 10:54
@stashcroft ok, thanks!

**Comment by ghost** [comment] 2013-11-10 14:05
OK. I've managed to make a flashable zip which only replaces the wifi module.
That way it will only break the wifi if it goes wrong and you can just reflash Mike's build.
It will only work with the 20131108 CM 10.2 build and I've only tested it on a single phone.
Not my fault if it goes horribly wrong etc.

http://www.qzxyz.com/wl12xx_update_20131108.zip

**Comment by JovieBrett** [comment] 2013-11-10 14:10
@stashcroft thank you!

**Comment by enveraltin** [comment] 2013-11-10 14:30
I've noticed that keeping bluetooth on causes a very similar battery drain
to keeping wifi on, it just can't go to deep sleep.

@stashcroft does this change affect the bluetooth too?

**Comment by ghost** [comment] 2013-11-10 14:45
This doesn't do anything with the bluetooth side of things.
If you install BetterBatteryStats what's the top kernel wakelock?

**Comment by mikeNG** [comment] 2013-11-10 14:59
wakelock change is uploaded here http://review.cyanogenmod.org/53389
will probably be included in next build for testing.

**Comment by ghost** [comment] 2013-11-10 15:22
Forgot to add. This only helps when I turn off 11n support on my AP.
Without this change I always see around 13% per hour drains.
With it it see as low as 1.8% per hour when the AP is doing b/g but 13% when doing b/g/n.

**Comment by mikeNG** [comment] 2013-11-10 20:44
@stashcroft does the wakelock change have any effect on interruptions?

**Comment by ghost** [comment] 2013-11-10 23:26
I think the whole change is a red herring and it was my testing method which in fact made it appear to fix things.
To test the HTC changes I ended up rebuilding the wl12xx and the other TI wifi module several times.
For those test I'd have to remove all the modules and then reload them with a modprobe wl12xx.
When I made just the simple wakelock type change I only removed the wl12xx module and not wl12xx_sdio, mac80211, cfg80211 or compat.

I've just gone back to the original version of the module and I see high drain on reboot.
If I then launch an adb shell and issue:

su
rmmod wl12xx
modprobe wl12xx

that fixes the high drain and I don't see any interruptions.

When I have high drain I see loads of:

wl12xx: WARNING Unable to flush all TX buffers, timed out (timeout 500 ms

in a dmesg.
After a module reload I don't see any of that.
Full dmesg here:

http://pastebin.com/VSTKEc2N

At 45.021789 the hardware seems to be reset and things seem to go wrong from there.
At 79.427001 I kick the rmmod.
At 83.456512 I load the module.
This time it come up properly with no hardware reset.
No timeout message and everything is fine.

I'm really confused now.
It must be something in one of the other modules isn't ready if you let modprobe load them all at boot time.

**Comment by ghost** [comment] 2013-11-11 18:09
I've done a bit more testing today. The key is to load wl12xx after wl12xx_sdio not before.
The problem with that is the rest of the system wants to load and unload wl12xx_sdio to turn the wifi on and off.
I've no idea how to change that.
Everytime the wifi is toggled I need to rmmod wl12xx; insmod wl12xx to fix everything.

**Comment by mikeNG** [comment] 2013-11-11 18:22
then something is going wrong...
all wl12xx devices have wl12xx.ko loaded all the time and wl12xx_sdio loaded & unloaded to turn wifi on and off

**Comment by ghost** [comment] 2013-11-13 21:18
The 20131112 build seems to not have the issue.
I've no idea why.

**Comment by ghost** [comment] 2013-11-19 19:31
Does the 20131112 build fix this for anybody else? It really did fix all the battery drain issues for me.
![screenshot_2013-11-19-19-29-07](https://f.cloud.github.com/assets/5838532/1575663/2ba126d0-5151-11e3-9ecd-ad3979c9bd03.png)

**Comment by enveraltin** [comment] 2013-11-20 14:19
Except for Bluetooth, yes.
Somehow this build is much more gentle on battery.

But Bluetooth is still the bummer for me, mango here.

On Tue, Nov 19, 2013 at 9:31 PM, stashcroft notifications@github.comwrote:

> Does the 20131112 build fix this for anybody else? It really did fix all
> the battery drain issues for me.
> [image: screenshot_2013-11-19-19-29-07]https://f.cloud.github.com/assets/5838532/1575663/2ba126d0-5151-11e3-9ecd-ad3979c9bd03.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/113#issuecomment-28824288
> .

## 

Enver

**Comment by lanmarc77** [comment] 2013-11-20 18:17
For BT drain see here: https://github.com/LegacyXperia/local_manifests/issues/15

**Comment by Institor666** [comment] 2013-11-21 00:40
Did you perform full wipe? For me it's not fixed in last build (20131112), battery drain still high.
And can anyone please test SIP (VoIP) over wifi? It's not working, log (dmesg) contains many of

```
<3>[  119.435485] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[  119.435791] wl12xx: Reading FW panic log
<6>[  119.436279] wl12xx: Hardware recovery in progress. FW ver: Rev 6.5.7.0.46
<6>[  119.436553] wl12xx: pc: 0x238
<6>[  119.436798] wl12xx: removing interface 84:00:d2:fb:87:28
<6>[  119.437042] wl12xx: removing interface 84:00:d2:fb:87:27
<6>[  119.441741] ieee80211 phy0: Hardware restart was requested
<6>[  119.443908] wl12xx: state: 0
<3>[  119.452087] [audio_pcm_in.c:audpcm_in_enc_config] sending AUDPREPROC_AUDREC_CMD_ENC_CFG command
<3>[  119.464691] [audio_acdb.c:acdb_fill_audpreproc_fluence] error in finding fluence block
<3>[  119.465148] [audio_acdb.c:acdb_calibrate_audpreproc] fluence block is not found
<6>[  120.175689] wl12xx: firmware booted (Rev 6.3.10.0.136)
<6>[  120.181060] wl12xx: state: 2
<6>[  120.181427] wl12xx: adding p2p mgmt vif
<6>[  120.223663] wl12xx: Association completed.
<3>[  120.247131] wl12xx: ERROR no active RX BA session on tid: 0
<7>[  120.247375] HW problem - can not stop rx aggregation for tid 0
<3>[  120.253875] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[  120.254241] wl12xx: Reading FW panic log
<6>[  120.254638] wl12xx: Hardware recovery in progress. FW ver: Rev 6.3.10.0.136
<6>[  120.255004] wl12xx: pc: 0x4bc
<6>[  120.255187] wl12xx: removing interface 84:00:d2:fb:87:28
<6>[  120.255493] wl12xx: removing interface 84:00:d2:fb:87:27
<6>[  120.261901] ieee80211 phy0: Hardware restart was requested
<6>[  120.266113] wl12xx: state: 0
<6>[  120.975952] wl12xx: firmware booted (Rev 6.3.10.0.136)
<6>[  120.981140] wl12xx: state: 2
<6>[  120.981292] wl12xx: adding p2p mgmt vif
<6>[  121.023620] wl12xx: Association completed.
<3>[  121.052612] wl12xx: ERROR watchdog interrupt received! starting recovery.
<6>[  121.053009] wl12xx: Reading FW panic log
<6>[  121.053375] wl12xx: Hardware recovery in progress. FW ver: Rev 6.3.10.0.136
<6>[  121.054046] wl12xx: pc: 0x4bc
<6>[  121.054229] wl12xx: removing interface 84:00:d2:fb:87:28
<6>[  121.054565] wl12xx: removing interface 84:00:d2:fb:87:27
<6>[  121.058685] ieee80211 phy0: Hardware restart was requested
```

etc. Should I create new thread for this?
p.s. - coconut, build 20131112, updated from previous without wipes. (this issue already exists in previous builds)

**Comment by ghost** [comment] 2013-11-21 09:52
I did a full wipe as I was experimenting with my own versions of the WLAN modules.

**Comment by mikeNG** [comment] 2013-12-28 01:16
I'm closing this issue since it has become an all-in-one battery drain discussion thread.
If you still have issues please file new bugs for separate issues.

**Closed as completed by mikeNG** 2013-12-28 01:16 UTC
