### ISSUE TITLE
Music skipping when being played

### ISSUE THREAD

**Issue by GianniDPC** [LegacyXperia/local_manifests#83] opened 2013-10-06 17:07 UTC
On Apollo and Google Play music, the music skips when being played, I tried different governors, setting the Min. frequency higher, But all of that didn't seem to help.

**Comment by mikeNG** [comment] 2013-10-10 03:50
Wait for next build and report back

**Comment by equillibrium** [comment] 2013-10-14 17:26
The new build (with the DSP switching off fix) brought music 'lags' every 15-20 seconds back. Previous build allowed to fix it with upping the CPU low frequency to 245, now it doesnt help the issue. Nightly build 20131010 - cm-10.1

**Comment by mikeNG** [comment] 2013-10-14 18:52
provide logs. music works just fine on my device since march 2013

**Comment by enveraltin** [comment] 2013-10-30 12:38
This happens every time on my XperiaMiniPro when Wifi is on and when I'm listening to music through bluetooth stereo headset. I'd be happy to help debugging this. I'm on cm-10.2_mango_LX-20131013-NIGHTLY.zip

**Comment by mspacek** [comment] 2013-11-05 21:50
If by skipping, the OP means short interruptions while playing, then I'm experiencing this as well on my Xperia Mini (cm10.1_smultron-LX-20131024-NIGHTLY). It seems random, but averages about one interruption every couple of minutes. Sometimes the interval between interruptions can be as little as 30 sec. Each interruption itself is maybe half a second long. I think this is a fairly recent development, over the course of the last month or so. Older versions of LegacyXperia cm10.1, maybe from August or Sept, didn't seem to do this.

I've tested with lots of different mp3s from lots of different albums, with both Apollo and Omich Player. I've only tested using **normal headphones**. I haven't touched the DSP manager. Everything there seems to be disabled and at defaults.

WiFi and GPS are always off.

Setting the min CPU freq to 245 MHz doesn't help. Changing the governor from ONDEMAND to PERFORMANCE doesn't help. I've left the I/O scheduler at (what I presume is the default) CFQ. Setting it to BFQ or SIO didn't help.

Which logs should I upload? Where would I find them on the file system?

Ah, I see from https://github.com/LegacyXperia/local_manifests/wiki/Changelog that the very latest 20131104 cm10.1 nightly may have addressed that. Hopefully I can try it out within a day and report back.

**Comment by mikeNG** [comment] 2013-11-05 22:32
@mspacek Users report that the issue is fixed on cm-10.1 and I tried it briefly on my cm-10.2 build and it seems to work fine. Let me know if you try it.

**Comment by mspacek** [comment] 2013-11-06 05:59
@mikeNG I've installed the cm10.1 smultron-LX-20131104-NIGHTLY, and I've been listening to interruption-free music ever since, so that seems to have fixed it. Thanks!

**Comment by mikeNG** [comment] 2013-11-06 12:11
So, I'm closing this

**Closed as completed by mikeNG** 2013-11-06 12:11 UTC

**Comment by mspacek** [comment] 2013-11-06 18:50
@mikeNG I may have jumped the gun. I'm starting to get interruptions again, though not as frequently. Maybe more like once every 10 minutes, though they seem to be getting more frequent over time. I wonder if this is a function of the amount of time after reboot, or amount of time spent playing music. Again, this is in both Apollo and Omich Player.

**Comment by equillibrium** [comment] 2013-11-07 04:02
yeah, with the latest build its back to the original state - skipping once every 10-15 mins, so it really is 'fixed' for me, not bothered at all! Awesome work!

**Comment by mspacek** [comment] 2013-11-07 04:05
Just to amend my previous comment, after listening all day, it seems it isn't getting more frequent with time. Just really really random, but very roughly once every 10-15 mins.
