### ISSUE TITLE
[Cm11] [coconut] [20151117] SD cache

### ISSUE THREAD

**Issue by Albrod** [LegacyXperia/local_manifests#1052] opened 2016-04-08 09:20 UTC
I want to make it faster, i know how to do it, but can't make it changes automatically on startup.
Any recommendation?
I make a file in /system/etc/init.d called 99sdcache i give it 777 permission and then i reboot.

This is what i write inside, this work for me in many ROM's

```
#!/system/bin/sh
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]
then
/system/xbin/echo "1024" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
fi;
```

**Comment by MardonHH** [comment] 2016-04-25 14:21
Hmm thats not a bug and this is the bugtracker.
You can set it with apps like kernel adiutor for example

And close this plz

**Closed as completed** 2016-04-25 17:05 UTC
