### ISSUE TITLE
No touchscreen after flashing the rom

### ISSUE THREAD

**Issue by Blorking** [LegacyXperia/local_manifests#19] opened 2013-08-18 11:37 UTC
After flashing the rom, the touch screen is not responding. 

I used a Xperia arc S with cm-10.2_anzu-LX-20130809-NIGHTLY and cm-10.2-20130815-UNOFFICIAL-anzu.

**Comment by dbodyas** [comment] 2013-08-18 20:29
I had some issues with touchscreen.
- [Issue 1](https://github.com/M66B/cm-xtended/issues/30)
- [Issue 2](https://github.com/nobodyAtall/msm7x30-3.4.x-nAa/issues/3)
- [Video](http://youtu.be/5znuJK5cURw)

How I fixed it

``` diff
diff --git a/arch/arm/mach-msm/board-semc_mogami.c b/arch/arm/mach-msm/board-sem
index 847f49c..b24cec6 100644
--- a/arch/arm/mach-msm/board-semc_mogami.c
+++ b/arch/arm/mach-msm/board-semc_mogami.c
@@ -4533,9 +4533,9 @@ static void __init mogami_temp_fixups(void)
 static void __init shared_vreg_on(void)
 {
 #ifdef CONFIG_MSM_UNDERVOLT_TOUCH
-       vreg_helper_on(VREG_L20, 2800);
+       vreg_helper_on(VREG_L20, 2630);
 #else
-       vreg_helper_on(VREG_L20, 3050);
+       vreg_helper_on(VREG_L20, 2800);
 #endif
        vreg_helper_on(VREG_L10, 2600);
 #ifdef CONFIG_MSM_UNDERVOLT_LCD
```

**Comment by mikeNG** [comment] 2013-08-18 20:38
@bodya-dnepr interesting. Did you have this issue with 2.6.32 kernel too?

**Comment by dbodyas** [comment] 2013-08-18 22:16
Only with kernel v3

**Comment by mikeNG** [comment] 2013-09-07 21:32
Try next build when it's out and see if the issue is still there

**Comment by n1kolaa** [comment] 2013-09-10 20:05
close this coz as i can se only he have isues,he can comile kernel with that changes for him self :+1:

**Comment by mikeNG** [comment] 2013-09-20 12:49
@Blorking Try the latest nightly and report if you still have the problem

**Comment by Blorking** [comment] 2013-09-21 07:09
@mikeNG same problem on the cm-10.2_anzu-LX-20130918-NIGHTLY.

**Comment by dbodyas** [comment] 2013-09-21 07:35
@Blorking try this one http://d.pr/f/k9Ls

**Comment by Blorking** [comment] 2013-09-21 08:41
@bodya-dnepr I flash this one in fastboot mode, and then go in CWM recovery. I made a factory reset/wipe cache, flash the rom and gapps. then, second factory reset/wipe cache and reboot. Finally, my touchscreen is always not responding.

**Comment by dbodyas** [comment] 2013-09-21 11:35
@Blorking, Did you replace the screen on your device?
My friend have the same issue as you.
Soon we'll try to compile the kernel to fit his device, stay tuned

**Comment by mikeNG** [comment] 2013-09-21 12:10
This is weird, the kernel should work fine, the voltages are the same as in the phone schematics & the factory 2.6 kernel. Maybe it is a hardware issue.

**Comment by Blorking** [comment] 2013-09-21 14:03
@bodya-dnepr Indeed, the previous owner replaced the screen. Please keep me in touch if you make progress for your friend's case.

**Comment by mikeNG** [comment] 2013-10-06 17:54
Hi,
Issue does not follow the rules (http://forum.xda-developers.com/showpost.php?p=46091341&postcount=3) and is automatically closed.

**Closed as completed by mikeNG** 2013-10-06 17:54 UTC

**Comment by dbodyas** [comment] 2013-10-31 12:27
@Blorking, my friend have "Arc" (without "S"). After flashing  "Arc S" ftf file the touchscreen works great.
Flash ftf file (try both "Arc S" and "Arc") before installing rom.
Hope this will fix your problem
