### ISSUE TITLE
[11][10.2] Mic is very low in Voxer, a walkie talkie app

### ISSUE THREAD

**Issue by taro-k** [LegacyXperia/local_manifests#589] opened 2014-05-06 06:43 UTC
Volume of microphone is lower than other phone when I use a walkie talkie application, Voxer, with cm-11 and cm-10.2 hallon.

The problem happens with both of 2 ROMS:
*cm-10.2-20140304-RELEASE-LegacyXperia-hallon.zip
*cm-11-20140417-UNOFFICIAL-LegacyXperia-hallon.zip (self built)

I cannot find any mic volume control, so I guess the fuction of auto volume adjustment may fail?

I am not sure to pull out appropriate logs but, with the cm-10.2, `$ adb logcat` looks like

```
I/ActivityManager(  543): Displayed com.rebelvox.voxer/.ConversationDetailList.ConversationDetail: +377ms
I/AudioService(  543):  AudioFocus  requestAudioFocus() from android.media.AudioManager@41a03f28com.rebelvox.voxer.System.SystemAudioManager$2@419f6bc0`
D/AudioHardware7x30(  233): AudioHardware::openInputStream devices 400000 format 1 channels 16 samplerate 16000
D/AudioHardware7x30(  233): AudioStreamInMSM72xx::standby()
I/AudioHardware7x30(  233): do input routing device 400000
I/AudioHardware7x30(  233): Routing audio to Speakerphone
I/AudioHardware7x30(  233): do input routing device 400000
I/AudioHardware7x30(  233): Routing audio to Speakerphone
D/AudioHardware7x30(  233): new_rx = 17
D/AudioHardware7x30(  233): new_tx = 12
D/AudioHardware7x30(  233): case PCM_REC
```

In contrast, Voxer's mic works well with original Galaxy Nexus with the log like

```
I/AudioService(  375):  AudioFocus  requestAudioFocus() from android.media.AudioManager@424d2f20com.rebelvox.voxer.System.SystemAudioManager$2@424d3718
I/AudioService(  375):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@424d2f20com.rebelvox.voxer.System.SystemAudioManager$2@424d3718
```

**Comment by nguyentrunght** [comment] 2014-05-17 00:41
same here, it still happen to the CM11-20140512.
Hope dev team can fix soon. this is one of fundamental function for a mobile device.

**Comment by mikeNG** [comment] 2014-06-03 18:57
Duplicate of #547
I will try to fix this

**Closed as completed by mikeNG** 2014-06-03 18:57 UTC
