### ISSUE TITLE
[CM11]-20140611-urushi

### ISSUE THREAD

**Issue by esemef** [LegacyXperia/local_manifests#663] opened 2014-06-12 13:09 UTC
Screen-off animation style disabled doesn't work. It uses the last animation style that was selected.

**Comment by 16D** [comment] 2014-06-12 14:04
I have posted same issue in anzu and mango with 20140611 build:
https://github.com/LegacyXperia/local_manifests/issues/654

There was no problem in 20140603/20140604 build.

**Comment by mikeNG** [comment] 2014-06-12 17:42
Duplicate of #654

will be fixed in next build

**Comment by 16D** [comment] 2014-06-12 21:17
I have found cm-11-20140612 build for anzu and now it works correct.

**Closed as completed** 2014-06-12 21:26 UTC
