### ISSUE TITLE
[cm11] Lagging while browsing images (browser - google search)

### ISSUE THREAD

**Issue by DoctorMorph** [LegacyXperia/local_manifests#226] opened 2013-12-04 15:05 UTC
While browsing images on google search or browser the app begin to lag and it's impossible to handle it. How can i fix this issue?
Also, launcher3 is a bit laggy too. Especially the fade-in drawer animation... It's normal?

[cm11-20131127-anzu] Xperia Arc S

**Comment by mikeNG** [comment] 2013-12-04 15:28
Again, Duplicate of #181

**Closed as completed by mikeNG** 2013-12-04 15:28 UTC
