### ISSUE TITLE
Plz Help!!  Problem with Back button CM 11.0 SE Live With Walkman (WT19i) .... Any Fix?

### ISSUE THREAD

**Issue by sean024** [LegacyXperia/local_manifests#633] opened 2014-06-03 17:21 UTC
Hi,

I'm currently using CM 11.0 on my WT19i, and I'm really having problems with my Back key.  The Back key touch doesn't work most of the time.  I have to restart my phone every time it stops working.  After disconnecting a phone call my Back key stops working and sometimes it stops randomly.

I've installed the stock ROM for the LWW and tried to use the Back key and it works fine, so it can't be a hardware issue, I've also installed the different updates of CM 11.0 and it's all the same issue.

I really like the feel of using CM 11.0 on my phone and I want to keep it, please can someone help me in getting this fixed.

Thanks

**Comment by godlesplay** [comment] 2014-06-03 17:50
for me back key doesn't work when I have now keyboard app checked in settings, when?:
-I removed aosp keyboard
-installed swiftkey
-updated swiftkey, then swiftkey is not checked in settings and back button is not working, when I check swiftkey back button is working again

**Comment by mikeNG** [comment] 2014-06-03 17:53
Duplicate of #12

**Closed as completed by mikeNG** 2014-06-03 17:53 UTC
