### ISSUE TITLE
Very high RAM space consumption on coconut cm10.2-20130829

### ISSUE THREAD

**Issue by LillyWho** [LegacyXperia/local_manifests#58] opened 2013-09-10 14:23 UTC
this is happening although no app is running and no apps are starting at/after boot

free: 75-174mb
full: 205 mb and sometimes up

is this caused by the very limited capacity of the device or the the mighty consumption of the newest android version?
may i reconfigure the memory manager?

**Comment by mikeNG** [comment] 2013-09-20 12:53
This is not a bug, our ram is limited and we already did the best we could to free up ram. I'm closing the issue since there is no way to improve ram management without spending weeks of searching.

**Closed as completed by mikeNG** 2013-09-20 12:53 UTC
Labels: wontfix
