### ISSUE TITLE
Nightly 20140907 Xperia Ray: Still Bt Battery drain when enabled

### ISSUE THREAD

**Issue by the-dreamer** [LegacyXperia/local_manifests#783] opened 2014-09-08 09:47 UTC
My hope was that this bt battery drain is fixed finally. But unfortunately is not really fixed when bt is enabled. Yes, if i disable BT by widget the battery drain stops. I don't need to reboot the phone anymore. 

But with activated Bt the phone will never goes into deep sleep. BetterBatteryStats says that msm_seria_hs_dma keeps a kernel wakelock. 
I am aware that an activated bt will comsume more power, but when the phone is not connected via bt i think the current behaviour is wrong. 

My ray is now running over 30 minutes with the new rom version. 
After some googeling i found this here (https://blog.cryptomilk.org/2012/05/06/cm9-android-4-0-ics-and-deep-sleep/) and couldn't see it in git for LX. I don't know if it is practicable for our devices.

**Comment by mikeNG** [comment] 2014-09-08 17:24
We must choose between msm_serial_hs_dma wakelock and rpcrotuer_smd_xprt wakelocks. I choose the first, since it only affects battery when BT is enabled.

This is a really hard issue for me to fix, I don't think anything more can be done after researching for more than a year.

**Comment by the-dreamer** [comment] 2014-09-09 09:14
Is the value in config.xml already setted in LX? In the repository from nobadyAtall it is:

https://github.com/nobodyAtall/android_device_semc_mogami-common/blob/jellybean/overlay/frameworks/base/core/res/res/values/config.xml

**Comment by mikeNG** [comment] 2014-09-09 17:16
The value you are mentioning does nothing on android 4.2+, it's been discussed many times.

**Comment by the-dreamer** [comment] 2014-09-10 07:20
Okay, i didn't know both, sorry.

**Comment by psyke83** [comment] 2014-09-12 09:16
Mike, hacking the kernel is probably the wrong approach. You need to create a proper Bluedroid vendor config.

I can't find BOARD_BLUEDROID_VENDOR_CONF in mogami-common, smultron or msm7x30-common (searching via github), so your devices are using vnd_generic.txt. Take that file as your template, and install it into a device config and point to it using the boardconfig I mentioned above. Here's the file: https://github.com/CyanogenMod/android_hardware_broadcom_libbt/blob/cm-11.0/include/vnd_generic.txt

Now add the following lines:
LPM_BT_WAKE_POLARITY = 0
LPM_HOST_WAKE_POLARITY = 0

Actually, you may need to use trial and error, as only one of those may be needed. Both are set to 1 (active high) by default in the source, so this will set them to active low. This will hopefully solve the wakelock in the correct way (and it goes without saying, if you added any hacks to the BT kernel drivers, you should probably revert).

**Comment by rtammekivi** [comment] 2014-09-12 09:33
the vnd_ file is for vendor specific bt enhancements (in libbt-vendor). TI does not have these flags, they are for Broadcom bt vendor library.

**Comment by psyke83** [comment] 2014-09-12 10:10
Damn, I completely forgot that it wasn't a Broadcom chipset - sorry for the spam. I looked at the TI vendor lib and there's no implementation for BT wake there. You probably know that already, I guess.

**Comment by mikeNG** [comment] 2014-09-12 12:07
The kernel hacks I pushed don't actually work anyway, the device still doesn't enter deep sleep when BT is enabled. The problem is that I don't have the time to look into how things work to try and fix the issue. Some help would be nice here, I can't fix everything myself

**Comment by the-dreamer** [comment] 2014-10-07 10:38
fyi: new Nightly and no changes.

**Comment by mikeNG** [comment] 2015-03-01 19:41
From some research I made, according to the datasheets the wl12xx BT wake pin isn't connected on our devices. I can't figure out how to fix this properly.

**Comment by L3RAT** [comment] 2015-03-15 20:58
Is that change necessary? Thats the only one made in st_kim.c, which does not make sense to me...

https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commit/b00e126ffea89b687a83093546058b07aa054b4c

**Comment by mikeNG** [comment] 2015-03-26 19:34
Possible fix: http://review.msm7x30.org/285

**Comment by the-dreamer** [comment] 2015-04-03 07:45
Confirmed. Bluetooth is enabled and Phone goes to deep sleep. Thank you very much!
The new update [CM12] is now running for more then 12 hours.

**Comment by mikeNG** [comment] 2015-04-03 19:06
Fix merged in all branches. Closing this for now, my testing also shows that it's fixed :)

**Closed as completed by mikeNG** 2015-04-03 19:06 UTC
Labels: bug, highpriority, cm-11.0
