### ISSUE TITLE
CM 11 Nightly nightly 20131127 (HAIDA) GPS Remains Always on

### ISSUE THREAD

**Issue by Nikhildangui** [LegacyXperia/local_manifests#243] opened 2013-12-06 18:12 UTC
GPS working and locking fine but GPS switching on and off and also Location services has some Bugs

1) When any app requests for Location access and if Location is turned on (GPS cant     be turned on or off in KITKAT but you have manage it in location settings, right??) so when location is turned on and when its turned off from settings menu, GPS still continues to run consuming Battery, as proved by below Graph.
Note: GPS remains on only if its used by or if it is ever turned ON by any app to get location, i observed it twice

2) Location MODE changes after turning Location ON and OFF, i keeps it on battery saving location mode but it goes back to Device only mode every time i turn on and off loaction services

Hope below attached screen shot will Help, if Logs are needed ill try to provide, i never took logs, and dont know how to, Sorry MIke if this is not Helpful

![b5c15216-5ea0-11e3-9e83-503a5a22d438](https://f.cloud.github.com/assets/6098030/1698805/c9719db2-5f67-11e3-9e73-108e976e1f4d.png)

**Comment by mikeNG** [comment] 2013-12-08 20:45
Duplicate of #161 
Solution: Never turn off GPS from settings, android manages gps better itself

**Closed as completed by mikeNG** 2013-12-08 20:45 UTC

**Comment by Nikhildangui** [comment] 2013-12-09 14:30
mike i had read that issue and had doubt that u may mark this as Duplicate but i still reported it as earlier this issue was reported in CM 10.x where is this is CM11 
anways thanks for your work...
you going Great
