### ISSUE TITLE
SystemUI restarting [CM11 Nightly build 20140603-Smultron]

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#635] opened 2014-06-04 14:31 UTC
Just scrolling the newsfeed on Facebook then suddenly SystemUI restarts (no force closes regarding the SystemUI.apk, it just restarted)
This issue was actually happened at about 2 times now on the latest Nighty build on Smultron.
Log: http://pastebin.com/DYXw0cDc

**Comment by mikeNG** [comment] 2014-07-30 15:54
Still an issue? couldn't reproduce it since you reported it

**Comment by JovieBrett** [comment] 2014-07-30 17:10
@mikeNG Honestly, it's still an issue here but it's rarely happening unlike those previous builds with a huge issue in systemui restarts, can't easily catch a log. I also have this systemui restarting on my Grouper with the latest CM11 nightly build, I guess this is an issue with CM's side.

**Comment by fqdb** [comment] 2014-07-30 18:46
For the latest build it only occurs sometimes when running a heavy app (like games).

**Comment by mikeNG** [comment] 2014-08-30 15:49
It's a global CM issue probably related to the theme engine. Not something I can do about it.

**Comment by JovieBrett** [comment] 2014-08-30 17:05
@mikeNG ok then, so is it ok if I'll close this issue now? haven't had any systemui restarts for awhile now :)

**Comment by fqdb** [comment] 2014-09-01 09:40
I still have them, it's probably related to OOM, when the foreground app is drawing all memory and systemUI is closed by the memory management. Maybe the issue is due to the KK memory management, as I never had this issue on <4.4. (instead it would soft reboot the device, so looking at it like that, it's better now).

**Comment by JovieBrett** [comment] 2014-09-01 09:55
@sdk16420
I honestly have this issue too but it's happening just for once unlike the previous builds with a huge problem in a continous system ui restarts. Just noticed one thing whenever the systemui will restart, the device will be in deadlock state then after the systemui restarts, the device will look like it have refreshed from a laggy state before which does a good thing also. Thank goodness systemui is the one that crashes instead of the past issues were soft rebooting is the problem. Thanks about the infos man.

**Comment by Diaz1999** [comment] 2014-09-19 05:48
sometimes it hangs when playing (not) very heavy games like Minecraft in my coconut btw
cm-11-20140906-UNOFFICIAL-LegacyXperia-coconut

**Comment by mikeNG** [comment] 2014-09-19 20:11
Minecraft IS a heavy game

**Comment by Diaz1999** [comment] 2014-10-08 14:17
but it's just one and the only game that installed on my device, sorry
cm-11-20140906-UNOFFICIAL-LegacyXperia-coconut

**Closed as completed** 2015-03-01 19:59 UTC
Labels: bug, cm-11.0
