### ISSUE TITLE
Sleep of death on CM11 iyokan.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#913] opened 2015-04-16 02:59 UTC
I have mounts2sd remounting applications and libraries. A lot of times the phone will not wake up after going into deep sleep.

https://gist.github.com/pteek/e72b43dc0d800a58d0da

I am on latest CM1120150406. I have a new Samsung EVO class10 sd card.

**Comment by rtsui-harmonicinc** [comment] 2015-04-18 02:26
I found that I have similar problem these days with 20150406 as well.
I plugged in my phone to the charger till the next day and then on the next day I found that my phone was keeping the green led on even I have removed it from the charger and nothing could wake the phone up. And, therefore I tried the key combo to restart the phone but that doesn't work, I could only get my phone back to work by battery-pulling.

**Comment by mikeNG** [comment] 2015-04-18 19:54
Log doesn't contain anything useful but this is a known issue.

**Comment by mikeNG** [comment] 2015-04-18 20:22
Looks duplicate of #885

**Closed as completed by mikeNG** 2015-04-18 20:22 UTC
