### ISSUE TITLE
Some bugs to FixIt

### ISSUE THREAD

**Issue by Geil** [LegacyXperia/local_manifests#31] opened 2013-08-27 13:53 UTC
Hey, good job! Thank you very much, man!

SEMC Xperia Mini ST15i on CM10.2 from 2013-08-19.
Russia, St. Petersburg.

But unfortunately there are a few bugs... Here is some of it:
1.1. Already talked about the camera... Standard app: preview is buggy, but works... sorry, I can't assess how well. Hm...
1.2. Focal: good app (in potential), but very VERY unstable: some crashes are BIG annoying.
1.2.1. HDR don't works correctly (at lest in auto-mode) - the camera simply takes three shots at different exposures, without putting them on top of each other.
1.2.2. Video don't works - appcrash!
1.2.3. PicSphere don't works... preview as bad as standard app too, tap on shot-button - appcrash.
1.2.4. Panorama don't works ;(((((
2. Google Play Market 4.3.11 don't works - without crash alarm message or ANR, just... tap on him - and the app closes instantly. And doesn't matter whether the app system or user.
3. Tap on SELinux in Settings - freeze and reboot (O_O)
4. Display autobrightless don't works correctly - it needs a very bright light, so that the phone realized that I needed to make the screen brighter. If the light is off - display will still be at the same brightness. Maybe I'm doing something wrong? And I'm a fool, and everything is as it should be? oO
5. I don't know why but device don't works with some SIM-cards. I mean... Displays the alarm "com.android.phone stopped" (or something like that) and the device can not detect the network + the status bar can not be lowered for example (oO). Everything works fine with the SIM card from the operator "MTS" ("Mobile TeleSystems") (2G and 3G network names "MTS-RUS").
Inserted the SIM card from operator MegaFon - the problems started, sensor rarely responds to touch.
Where is the problem - in SIM-card or in device?

That's not all, but I could not remember everything at once.

Excuse me, please, if something was not clear - I'm still not adequately speak English ...)

Fix it :) Good luck!

**Comment by mikeNG** [comment] 2013-08-27 14:03
1 Camera is still WIP, we are lucky it works like this for now.
3 This is not a bug, it's a feature (don't ask me why, CM decided to do so)
4 Will be improved in next build.
5 Provide logs & modem logs so we can find out any potential issues

Check the changelog for next build, it will contain many things I fixed.

**Comment by Geil** [comment] 2013-08-27 19:20
Hm... I'm sorry that I can ask stupid questions, but Google Play is not scheduled to work? I only just now realized how much I need it: D

**Comment by mikeNG** [comment] 2013-08-27 20:53
sorry I posted the wrong numbers... you can see the correct numers above now

**Comment by Geil** [comment] 2013-08-27 22:32
Hm... But the question about a Google Play is still opened :(

**Comment by Geil** [comment] 2013-08-27 22:33
Accidentally closed the topic, I'm sorry.

**Comment by mikeNG** [comment] 2013-08-27 22:39
I think it works fine here... I will try again and report. Also, a new build is coming.

**Comment by Geil** [comment] 2013-08-28 01:13
Your device - Xperia Mini?
And GPlay works on him?
If you check it (working gplay on xperia mini or not), it will be nice, because I don't understand why that's happening.
I have no way to check it on devices from my friends too - they have not devices xperia 2011 line.

Report me please.
And I look forward to the new build) Works as a whole effectively and quickly, but still a little... hm... wet :(

**Comment by Geil** [comment] 2013-08-28 07:28
Solved the problem with Google Play. Thank you :)
I'll let you know if I find more bugs.

**Comment by mikeNG** [comment] 2013-09-07 21:37
I'm closing this issue. Please open seperate tickets for each bug so we can close each bug when it's fixed.

**Closed as completed by mikeNG** 2013-09-07 21:37 UTC
