### ISSUE TITLE
[CM13.0][20160417][anzu] SMS/Text messages stopped

### ISSUE THREAD

**Issue by arpcpro** [LegacyXperia/local_manifests#1094] opened 2016-09-22 10:08 UTC
Open Messaging --> 3 dots --> Settings --> Scroll down --> Advanced --> Unfortunately, Messaging has stopped

![screenshot_20160922-113756](https://cloud.githubusercontent.com/assets/17868951/18744030/5545f8ba-80bc-11e6-9c0d-dc411db1e2da.png)

After installing the ROM I imported from SMS Backup around 5000 messages. I don't know if that caused the problem. But I have already deleted them all and I still cannot configure SMS advanced settings.

bugreport.pdf should be renamed to bugreport.zip (this forum was not allowing me to upload zip extention)
[bugreport.pdf](https://github.com/LegacyXperia/local_manifests/files/486972/bugreport.pdf)

[kmsg.txt](https://github.com/LegacyXperia/local_manifests/files/486986/kmsg.txt)
[last_kmsg.txt](https://github.com/LegacyXperia/local_manifests/files/486987/last_kmsg.txt)
[logcat.txt](https://github.com/LegacyXperia/local_manifests/files/486988/logcat.txt)
[radio.txt](https://github.com/LegacyXperia/local_manifests/files/486989/radio.txt)
[system.txt](https://github.com/LegacyXperia/local_manifests/files/486990/system.txt)

**Comment by slonopotamus** [comment] 2016-09-27 07:10
Confirming this on CM13.0/20160418@iyokan.

**Comment by slonopotamus** [comment] 2016-09-27 07:43
This is a duplicate of #1077

**Closed as completed** 2016-09-27 13:47 UTC
