### ISSUE TITLE
 Alpha build 3 20131127 - cm-11.0 CAMERA - (urushi) 

### ISSUE THREAD

**Issue by Dilesh** [LegacyXperia/local_manifests#280] opened 2013-12-13 05:28 UTC
video recording lags/ freeze and no video record saved. also camera sense words misplaced. 

![2447383](https://f.cloud.github.com/assets/5960987/1740019/991d11d4-63b6-11e3-831b-5dc621528bdc.jpg)

Log attached . hope its correct to find the issue. thanks

http://pastebin.com/JMi4FqK5

**Comment by mikeNG** [comment] 2013-12-13 19:05
Duplicate of #267

**Closed as completed by mikeNG** 2013-12-13 19:05 UTC
