### ISSUE TITLE
Battery drain from default messaging app

### ISSUE THREAD

**Issue by nezirus** [LegacyXperia/local_manifests#330] opened 2013-12-23 14:41 UTC
Phone: Xperia Mini Pro
ROM: cm-10.2_mango-LX-20131204-RELEASE

Steps to reproduce:
1) Recharge phone battery to 100%
2) Restart phone
3) Send one or more SMS messages 
...
Phone battery drains in about 24 hours, more than 50% spent by messaging app.

When not using messaging, or when manually removing messaging from recently used applications, battery lasts more than 48 hours.

Can I provide more info?

**Comment by piotrwie** [comment] 2013-12-23 17:23
duplicate of Issue #171

**Closed as completed** 2013-12-23 19:25 UTC

**Comment by piotrwie** [comment] 2013-12-23 20:01
MikeNG, are you sure issue is solved? true, I did not observe it yet on 131216, but it was present on previous releases... it happen in my case when mms was ready for me, I had auto-retreive of mms switched on. the mms did not come for good few hours, but messaging app drained half of battery in few hours.

**Comment by nezirus** [comment] 2013-12-29 09:11
It was triggered by MMS on my side also. There is a configuration option to send SMS messages via MMS when multiple recipients are detected. I don't have MMS activated, and that message failed, eating battery until I deleted it manually. There was no indication messaging app is trying to send that message again and again.
