### ISSUE TITLE
ROM update with lots of linked apps (Link2sd)

### ISSUE THREAD

**Issue by maystar** [LegacyXperia/local_manifests#766] opened 2014-08-19 09:55 UTC
I use the cm-11 rom on my haida phone. Because of the tiny internal memory I have nearly every app linked to the sd card using Link2SD. This works quite nice. But on each ROM upgrade all apps are updated too and the link at least for the dalvik cache is replaced by the actual file. So after first reboot with the mount script my phone is running out of memory and is hardly responding. And lots of apps (I've around 140) will not be updated. 
It follows a very time consuming loop of starting Links2SD, relink as much as possible, reboot the system, start Links2SD... This is an annoying and very time consuming task, which let's me think twice to upgrade my system. 
Has anybody a good workaround for this issue?

**Comment by avinashrocks1990** [comment] 2014-08-19 11:55
Use mounts2sd after upgrade just install the app and script then restart your phone

**Comment by s-kostyuk** [comment] 2014-08-22 17:30
Clean data and system partitions first (uninstall some preinstalled applications), then recreate mount script and reboot. It must help

**Comment by MardonHH** [comment] 2014-09-04 21:54
Tis is not a bug!
@mikeNG 
close this

**Closed as completed** 2014-09-04 22:56 UTC
