### ISSUE TITLE
Cm11 (Coconut) Message app crashes

### ISSUE THREAD

**Issue by anoopg87** [LegacyXperia/local_manifests#472] opened 2014-02-11 05:31 UTC
In Latest build 20140203 the Message app crashes. when i click the message it shows Unfortunately Messaging has stoped. Even i tried the default Messaging app to hangout. It shows the same

Best Regards,
Anoop Gopopalkrishnan

**Comment by mokkin** [comment] 2014-02-11 20:43
Duplicate of #473

**Closed as completed** 2014-02-11 20:45 UTC
