### ISSUE TITLE
slow kernel coconut cm-11.0

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#588] opened 2014-05-04 23:32 UTC
I'm using the latest kernel from the CM11 zip package.. 
Phone has very long startup: boot screen shows up for about a minute and then boots the system, CWM always freeze when loading for a minute and then show available options.

Sorry for my English, but I'm from Poland

**Comment by ankurjain093** [comment] 2014-05-07 06:54
this is a very old reported problem... 
this has been fixed with the ion kernel ... just wait for it ...
let mike do his job ....

**Comment by mikeNG** [comment] 2014-05-12 13:40
Please try latest build and provide logs if this still happens

**Comment by mikeNG** [comment] 2014-05-12 13:45
Also, duplicate of #383

**Closed as completed by mikeNG** 2014-05-12 13:45 UTC
